// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTCollectionTypes : NSObject
- (nonnull instancetype)initWithIntList:(nonnull NSArray<NSNumber *> *)intList stringList:(nonnull NSArray<NSString *> *)stringList intSet:(nonnull NSSet<NSNumber *> *)intSet stringSet:(nonnull NSSet<NSString *> *)stringSet intIntMap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)intIntMap stringStringMap:(nonnull NSDictionary<NSString *, NSString *> *)stringStringMap;
+ (nonnull instancetype)collectionTypesWithIntList:(nonnull NSArray<NSNumber *> *)intList stringList:(nonnull NSArray<NSString *> *)stringList intSet:(nonnull NSSet<NSNumber *> *)intSet stringSet:(nonnull NSSet<NSString *> *)stringSet intIntMap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)intIntMap stringStringMap:(nonnull NSDictionary<NSString *, NSString *> *)stringStringMap;
@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * intList;
@property (nonatomic, readonly, nonnull) NSArray<NSString *> * stringList;
@property (nonatomic, readonly, nonnull) NSSet<NSNumber *> * intSet;
@property (nonatomic, readonly, nonnull) NSSet<NSString *> * stringSet;
@property (nonatomic, readonly, nonnull) NSDictionary<NSNumber *, NSNumber *> * intIntMap;
@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * stringStringMap;
@end
