// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTBaseRecord.h"
#import "TSTBinaryTypes.h"
#import "TSTCollectionTypes.h"
#import "TSTOptionalTypes.h"
#import "TSTParentType.h"
#import "TSTPrimitiveTypes.h"
@interface TSTHelper : NSObject
+ (nonnull TSTPrimitiveTypes *)getPrimitiveTypes:(nonnull TSTPrimitiveTypes *)recordType;
+ (nonnull TSTCollectionTypes *)getCollectionTypes:(nonnull TSTCollectionTypes *)recordType;
+ (nonnull TSTOptionalTypes *)getOptionalTypes:(nonnull TSTOptionalTypes *)recordType;
+ (nonnull TSTBinaryTypes *)getBinaryTypes:(nonnull TSTBinaryTypes *)recordType;
+ (nonnull TSTBaseRecord *)getCppBaseRecord;
+ (nonnull TSTBaseRecord *)getHostBaseRecord:(nonnull TSTBaseRecord *)recordType;
+ (nonnull TSTParentType *)getNestedType:(nonnull TSTParentType *)parent;
@end
