// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTNestedType : NSObject
- (nonnull instancetype)initWithA:(int32_t)a b:(nonnull NSArray<NSArray<NSNumber *> *> *)b;
+ (nonnull instancetype)nestedTypeWithA:(int32_t)a b:(nonnull NSArray<NSArray<NSNumber *> *> *)b;
@property (nonatomic, readonly) int32_t a;
@property (nonatomic, readonly, nonnull) NSArray<NSArray<NSNumber *> *> * b;
@end
