// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTNestedType.h"
@interface TSTParentType : NSObject
- (nonnull instancetype)initWithNested:(nonnull TSTNestedType *)nested;
+ (nonnull instancetype)parentTypeWithNested:(nonnull TSTNestedType *)nested;
@property (nonatomic, readonly, nonnull) TSTNestedType * nested;
@end
