// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni

#import <Foundation/Foundation.h>
//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "SFTPlatformInterface.h"
#import "SFTNoParametersNoReturnCallback.h"
#import "SFTThrowingCallback.h"
#import "SFTCalculator.h"
#import "SFTDeprecationTest.h"
#import "SFTDeprecatedMethodTest.h"
#import "SFTOptionalInterface.h"
