// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTCalculator.h"
#import "SFTNoParametersNoReturnCallback.h"
#import "SFTPlatformInterface.h"
#import "SFTThrowingCallback.h"
NS_SWIFT_NAME(Calculator)
@interface SFTCalculator : NSObject
+ (nonnull SFTCalculator *)getInstance
  NS_SWIFT_NAME(getInstance());
/// adds up two values
/// 
/// - Parameter a: the first value
/// - Parameter b: the second value
/// - Returns: the sum of both values
- (int8_t)add:(int8_t)a b:(int8_t)b
  NS_SWIFT_NAME(add(a:b:));
- (int8_t)getPlatformValue:(nonnull id<SFTPlatformInterface>)platform
  NS_SWIFT_NAME(getPlatformValue(platform:));
- (void)noParametersNoReturn
  NS_SWIFT_NAME(noParametersNoReturn());
- (void)throwingException:(NSError* _Nullable * _Nonnull)error
  __attribute__((swift_error(nonnull_error)))
  NS_SWIFT_NAME(throwingException());
- (void)noParametersNoReturnCallback:(nonnull id<SFTNoParametersNoReturnCallback>)callback
  NS_SWIFT_NAME(noParametersNoReturnCallback(callback:));
- (void)throwingCallback:(nonnull id<SFTThrowingCallback>)callback error:(NSError* _Nullable * _Nonnull)error
  __attribute__((swift_error(nonnull_error)))
  NS_SWIFT_NAME(throwingCallback(callback:));
@end
