// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(DeprecatedMethodTest)
@protocol SFTDeprecatedMethodTest 
- (BOOL)deprecatedTestMethod
  DEPRECATED_MSG_ATTRIBUTE("this method is deprecated but the type is not")
  NS_SWIFT_NAME(deprecatedTestMethod());
@end
