// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTOptionalInterface.h"
NS_SWIFT_NAME(OptionalInterface)
@interface SFTOptionalInterface : NSObject
+ (nullable SFTOptionalInterface *)getInstance
  NS_SWIFT_NAME(getInstance());
+ (nullable SFTOptionalInterface *)getNullInstance
  NS_SWIFT_NAME(getNullInstance());
- (nullable NSString *)optionalParameter:(nullable NSString *)param
  NS_SWIFT_NAME(optionalParameter(param:));
- (nullable NSString *)optionalNullParameter:(nullable NSString *)param
  NS_SWIFT_NAME(optionalNullParameter(param:));
@end
