// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(NoParametersNoReturnCallback)
@protocol TSTNoParametersNoReturnCallback 
- (void)invoke
  NS_SWIFT_NAME(invoke());
@end
