// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(PlatformInterface)
@protocol TSTPlatformInterface 
- (int8_t)getValue
  NS_SWIFT_NAME(getValue());
@end
