// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'not_null.pydjinni'
#pragma once
#include "not_null_interface.hpp"
#include <gsl/pointers>
#include <memory>

namespace test::not_null_test {
class NotNullInterface {
public:
    virtual ~NotNullInterface() = default;
    static ::gsl::not_null<std::shared_ptr<::test::not_null_test::NotNullInterface>> get_instance() noexcept;
    virtual void not_null_parameter(const ::gsl::not_null<std::shared_ptr<::test::not_null_test::NotNullInterface>> & param) noexcept = 0;
};
} // namespace test::not_null_test
