// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTCppProperties.h"
@interface TSTCppProperties : NSObject
@property (readwrite) int64_t readwriteProperty;
@property (readonly, nonnull) NSString * readonlyProperty;
@property (readwrite, nullable) NSNumber * optionalProperty;
@property (readwrite, nonnull) NSArray<NSString *> * deprecatedProperty;
+ (nonnull TSTCppProperties *)getInstance;
- (void)changeReadonlyProperty;
@end
