// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTHostProperties.h"
#import "TSTHostPropertyHelper.h"
#import "TSTOptionalPropertyData.h"
#import "TSTReadonlyPropertyData.h"
#import "TSTReadwritePropertyData.h"
@interface TSTHostPropertyHelper : NSObject
+ (nonnull TSTHostPropertyHelper *)setup:(nonnull id<TSTHostProperties>)properties;
- (nonnull TSTReadwritePropertyData *)readwritePropertyData;
- (void)modifyHostReadwriteProperty;
- (nonnull TSTReadonlyPropertyData *)readonlyPropertyData;
- (nonnull TSTOptionalPropertyData *)optionalPropertyData;
@end
