// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
/// property class owned by the host language
@protocol TSTHostProperties <NSObject>
@property (readwrite) int64_t readwriteProperty;
@property (readonly, nonnull) NSString * readonlyProperty;
@property (readwrite, nullable) NSNumber * optionalProperty;
- (void)changeReadonlyProperty;
@end
