// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTOptionalPropertyData : NSObject
- (nonnull instancetype)initWithChangeCounter:(int32_t)changeCounter callbackValue:(nullable NSNumber *)callbackValue readValue:(nullable NSNumber *)readValue;
+ (nonnull instancetype)optionalPropertyDataWithChangeCounter:(int32_t)changeCounter callbackValue:(nullable NSNumber *)callbackValue readValue:(nullable NSNumber *)readValue;
@property (nonatomic, readonly) int32_t changeCounter;
@property (nonatomic, readonly, nullable) NSNumber * callbackValue;
@property (nonatomic, readonly, nullable) NSNumber * readValue;
@end
