// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTReadwritePropertyData : NSObject
- (nonnull instancetype)initWithChangeCounter:(int32_t)changeCounter callbackValue:(int64_t)callbackValue readValue:(int64_t)readValue;
+ (nonnull instancetype)readwritePropertyDataWithChangeCounter:(int32_t)changeCounter callbackValue:(int64_t)callbackValue readValue:(int64_t)readValue;
@property (nonatomic, readonly) int32_t changeCounter;
@property (nonatomic, readonly) int64_t callbackValue;
@property (nonatomic, readonly) int64_t readValue;
@end
