// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTReadonlyPropertyData : NSObject
- (nonnull instancetype)initWithChangeCounter:(int32_t)changeCounter callbackValue:(nonnull NSString *)callbackValue readValue:(nonnull NSString *)readValue;
+ (nonnull instancetype)readonlyPropertyDataWithChangeCounter:(int32_t)changeCounter callbackValue:(nonnull NSString *)callbackValue readValue:(nonnull NSString *)readValue;
@property (nonatomic, readonly) int32_t changeCounter;
@property (nonatomic, readonly, nonnull) NSString * callbackValue;
@property (nonatomic, readonly, nonnull) NSString * readValue;
@end
