// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.djinni'
#import <Foundation/Foundation.h>

typedef NS_ENUM(NSUInteger, ExampleEnum) {
    ExampleEnumA,
    ExampleEnumB,
    ExampleEnumC
} NS_SWIFT_NAME(ExampleEnum);
