// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'flags.pydjinni'
#include "example_flags.hpp"

namespace test::flags_test {
std::string to_string(::test::flags_test::ExampleFlags value) noexcept {
    std::string output;
    std::string separator = " | ";
    if((bool)(value & ::test::flags_test::ExampleFlags::A)) {
        if(!output.empty()) output += separator;
        output += "A";
    }
    if((bool)(value & ::test::flags_test::ExampleFlags::B)) {
        if(!output.empty()) output += separator;
        output += "B";
    }
    return output;
}
} // namespace test::flags_test
