// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'flags.djinni'
#import <Foundation/Foundation.h>

typedef NS_OPTIONS(NSUInteger, ExampleFlags) {
    ExampleFlagsA = 1u << 0,
    ExampleFlagsB = 1u << 1,
    ExampleFlagsAll = 0 | ExampleFlagsA | ExampleFlagsB,
    ExampleFlagsNone = 0
} NS_SWIFT_NAME(ExampleFlags);
