// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni

#import <Foundation/Foundation.h>
//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "SFTGlobalRecord.h"
#import "SFTGlobalInterface.h"
#import "SFTSomethingNamespacedNamespacedRecord.h"
#import "SFTSomethingNamespacedOtherNamespacedRecord.h"
#import "SFTSomethingNamespacedNamespacedInterface.h"
