// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTSomethingNamespacedNamespacedRecord.h"
NS_SWIFT_NAME(GlobalInterface)
@interface SFTGlobalInterface : NSObject
+ (nonnull SFTSomethingNamespacedNamespacedRecord *)getNamespacedRecord
  NS_SWIFT_NAME(getNamespacedRecord());
@end
