// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTSomethingNamespacedOtherNamespacedRecord.h"
NS_SWIFT_NAME(GlobalRecord)
@interface SFTGlobalRecord : NSObject
- (nonnull instancetype)initWithA:(nonnull SFTSomethingNamespacedOtherNamespacedRecord *)a;
+ (nonnull instancetype)globalRecordWithA:(nonnull SFTSomethingNamespacedOtherNamespacedRecord *)a;
@property (nonatomic, readonly, nonnull) SFTSomethingNamespacedOtherNamespacedRecord * a;
@end
