// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTGlobalRecord.h"
#ifndef __PYDJINNI_OBJC_NS_SomethingNamespaced
struct SomethingNamespaced {};
#define __PYDJINNI_OBJC_NS_SomethingNamespaced
#endif
NS_SWIFT_NAME(SomethingNamespaced.NamespacedRecord)
@interface SFTSomethingNamespacedNamespacedRecord : NSObject
- (nonnull instancetype)initWithA:(nonnull SFTGlobalRecord *)a;
+ (nonnull instancetype)namespacedRecordWithA:(nonnull SFTGlobalRecord *)a;
@property (nonatomic, readonly, nonnull) SFTGlobalRecord * a;
@end
