// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTGlobalRecord.h"
#ifndef __PYDJINNI_OBJC_NS_SomethingNamespaced
struct SomethingNamespaced {};
#define __PYDJINNI_OBJC_NS_SomethingNamespaced
#endif
NS_SWIFT_NAME(SomethingNamespaced.NamespacedInterface)
@interface SFTSomethingNamespacedNamespacedInterface : NSObject
+ (nonnull SFTGlobalRecord *)getGlobalRecord
  NS_SWIFT_NAME(getGlobalRecord());
@end
