// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTSomethingNamespacedOtherNamespacedRecord.h"
NS_SWIFT_NAME(GlobalRecord)
@interface TSTGlobalRecord : NSObject
- (nonnull instancetype)initWithA:(nonnull TSTSomethingNamespacedOtherNamespacedRecord *)a;
+ (nonnull instancetype)globalRecordWithA:(nonnull TSTSomethingNamespacedOtherNamespacedRecord *)a;
@property (nonatomic, readonly, nonnull) TSTSomethingNamespacedOtherNamespacedRecord * a;
@end
