// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTSomethingNamespacedNamespacedRecord.h"
NS_SWIFT_NAME(GlobalInterface)
@interface TSTGlobalInterface : NSObject
+ (nonnull TSTSomethingNamespacedNamespacedRecord *)getNamespacedRecord
  NS_SWIFT_NAME(getNamespacedRecord());
@end
