// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTGlobalRecord.h"
#ifndef __PYDJINNI_OBJC_NS_SomethingNamespaced
struct SomethingNamespaced {};
#define __PYDJINNI_OBJC_NS_SomethingNamespaced
#endif
NS_SWIFT_NAME(SomethingNamespaced.NamespacedRecord)
@interface TSTSomethingNamespacedNamespacedRecord : NSObject
- (nonnull instancetype)initWithA:(nonnull TSTGlobalRecord *)a;
+ (nonnull instancetype)namespacedRecordWithA:(nonnull TSTGlobalRecord *)a;
@property (nonatomic, readonly, nonnull) TSTGlobalRecord * a;
@end
