// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#ifndef __PYDJINNI_OBJC_NS_SomethingNamespaced
struct SomethingNamespaced {};
#define __PYDJINNI_OBJC_NS_SomethingNamespaced
#endif
NS_SWIFT_NAME(SomethingNamespaced.OtherNamespacedRecord)
@interface TSTSomethingNamespacedOtherNamespacedRecord : NSObject
- (nonnull instancetype)initWithA:(int32_t)a;
+ (nonnull instancetype)otherNamespacedRecordWithA:(int32_t)a;
@property (nonatomic, readonly) int32_t a;
@end
