// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
package test.record;

public class BaseRecordBase {
    final int value;
    public BaseRecordBase(
        int value
    ) {
        this.value = value;
    }

    public int getValue() { return value; }

}
