// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class CollectionTypes {
    final java.util.ArrayList<Integer> intList;
    final java.util.ArrayList<String> stringList;
    final java.util.HashSet<Integer> intSet;
    final java.util.HashSet<String> stringSet;
    final java.util.HashMap<Integer, Integer> intIntMap;
    final java.util.HashMap<String, String> stringStringMap;
    public CollectionTypes(
        java.util.ArrayList<Integer> intList,
        java.util.ArrayList<String> stringList,
        java.util.HashSet<Integer> intSet,
        java.util.HashSet<String> stringSet,
        java.util.HashMap<Integer, Integer> intIntMap,
        java.util.HashMap<String, String> stringStringMap
    ) {
        this.intList = intList;
        this.stringList = stringList;
        this.intSet = intSet;
        this.stringSet = stringSet;
        this.intIntMap = intIntMap;
        this.stringStringMap = stringStringMap;
    }

    public java.util.ArrayList<Integer> getIntList() { return intList; }
    public java.util.ArrayList<String> getStringList() { return stringList; }
    public java.util.HashSet<Integer> getIntSet() { return intSet; }
    public java.util.HashSet<String> getStringSet() { return stringSet; }
    public java.util.HashMap<Integer, Integer> getIntIntMap() { return intIntMap; }
    public java.util.HashMap<String, String> getStringStringMap() { return stringStringMap; }

    @Override
    public String toString() {
        return "test.record.CollectionTypes{" +
            "intList=" + intList +
            ",stringList=" + stringList +
            ",intSet=" + intSet +
            ",stringSet=" + stringSet +
            ",intIntMap=" + intIntMap +
            ",stringStringMap=" + stringStringMap +
        "}";
    }
}
