// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
package test.record;

public final class NestedType {
    final int a;
    final java.util.ArrayList<java.util.ArrayList<Integer>> b;
    public NestedType(
        int a,
        java.util.ArrayList<java.util.ArrayList<Integer>> b
    ) {
        this.a = a;
        this.b = b;
    }

    public int getA() { return a; }
    public java.util.ArrayList<java.util.ArrayList<Integer>> getB() { return b; }

    @Override
    public String toString() {
        return "test.record.NestedType{" +
            "a=" + a +
            ",b=" + b +
        "}";
    }
}
