// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
package test.record;

public final class OptionalTypes {
    final Integer intOptional;
    final String stringOptional;
    public OptionalTypes(
        Integer intOptional,
        String stringOptional
    ) {
        this.intOptional = intOptional;
        this.stringOptional = stringOptional;
    }

    public Integer getIntOptional() { return intOptional; }
    public String getStringOptional() { return stringOptional; }

    @Override
    public String toString() {
        return "test.record.OptionalTypes{" +
            "intOptional=" + intOptional +
            ",stringOptional=" + stringOptional +
        "}";
    }
}
