// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include "nested_type.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Record::CppCli {
public ref class NestedType sealed  {
public:
    NestedType(int a, System::Collections::Generic::List<System::Collections::Generic::List<int>^>^ b);

    property int A
    {
        int get();
    }
    property System::Collections::Generic::List<System::Collections::Generic::List<int>^>^ B
    {
        System::Collections::Generic::List<System::Collections::Generic::List<int>^>^ get();
    }
    System::String^ ToString() override;
internal:
    using CppType = ::test::record::NestedType;
    using CsType = NestedType^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    int _a;
    System::Collections::Generic::List<System::Collections::Generic::List<int>^>^ _b;
};
} // namespace Test::Record::CppCli
