// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include "collection_types.hpp"
#include "pydjinni/cppcli/Marshal.hpp"

namespace Test::Record::CppCli {
[System::Serializable]
public ref class CollectionTypes sealed  {
public:
    CollectionTypes(System::Collections::Generic::List<int>^ intList, System::Collections::Generic::List<System::String^>^ stringList, System::Collections::Generic::HashSet<int>^ intSet, System::Collections::Generic::HashSet<System::String^>^ stringSet, System::Collections::Generic::Dictionary<int, int>^ intIntMap, System::Collections::Generic::Dictionary<System::String^, System::String^>^ stringStringMap);

    property System::Collections::Generic::List<int>^ IntList
    {
        System::Collections::Generic::List<int>^ get();
    }
    property System::Collections::Generic::List<System::String^>^ StringList
    {
        System::Collections::Generic::List<System::String^>^ get();
    }
    property System::Collections::Generic::HashSet<int>^ IntSet
    {
        System::Collections::Generic::HashSet<int>^ get();
    }
    property System::Collections::Generic::HashSet<System::String^>^ StringSet
    {
        System::Collections::Generic::HashSet<System::String^>^ get();
    }
    property System::Collections::Generic::Dictionary<int, int>^ IntIntMap
    {
        System::Collections::Generic::Dictionary<int, int>^ get();
    }
    property System::Collections::Generic::Dictionary<System::String^, System::String^>^ StringStringMap
    {
        System::Collections::Generic::Dictionary<System::String^, System::String^>^ get();
    }

    System::String^ ToString() override;
internal:
    using CppType = ::test::record::CollectionTypes;
    using CsType = CollectionTypes^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    System::Collections::Generic::List<int>^ _intList;
    System::Collections::Generic::List<System::String^>^ _stringList;
    System::Collections::Generic::HashSet<int>^ _intSet;
    System::Collections::Generic::HashSet<System::String^>^ _stringSet;
    System::Collections::Generic::Dictionary<int, int>^ _intIntMap;
    System::Collections::Generic::Dictionary<System::String^, System::String^>^ _stringStringMap;
};
}  // namespace Test::Record::CppCli
