// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include "old_record.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Record::CppCli {
/**
 * <summary>
 * <para>deprecated record with comments</para>
 * </summary>
 */
[System::Obsolete]
public ref class OldRecord sealed  {
public:
    OldRecord(bool a);

    /**
     * <summary>
     * <para>more comment</para>
     * </summary>
     */
    property bool A
    {
        bool get();
    }
    System::String^ ToString() override;
internal:
    #pragma warning(suppress : 4996)
    using CppType = ::test::record::OldRecord;
    using CsType = OldRecord^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    bool _a;
};
} // namespace Test::Record::CppCli
