// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#import <Foundation/Foundation.h>

@class BaseRecord;
NS_SWIFT_NAME(BaseRecordBase)
@interface BaseRecordBase : NSObject
- (nonnull instancetype)initWithValue:(int32_t)value;
+ (nonnull instancetype)baseRecordBaseWithValue:(int32_t)value;
@property (nonatomic, readonly) int32_t value;
@end
