// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#import <Foundation/Foundation.h>

NS_SWIFT_NAME(BinaryTypes)
@interface BinaryTypes : NSObject
- (nonnull instancetype)initWithBinaryT:(nonnull NSData *)binaryT binaryOptional:(nullable NSData *)binaryOptional;
+ (nonnull instancetype)binaryTypesWithBinaryT:(nonnull NSData *)binaryT binaryOptional:(nullable NSData *)binaryOptional;
@property (nonatomic, readonly, nonnull) NSData * binaryT;
@property (nonatomic, readonly, nullable) NSData * binaryOptional;
@end
