// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#import <Foundation/Foundation.h>
#import "PrimitiveTypes.h"
#import "CollectionTypes.h"
#import "OptionalTypes.h"
#import "BinaryTypes.h"
#import "BaseRecordBase.h"

NS_SWIFT_NAME(Helper)
@interface Helper : NSObject
+ (nonnull PrimitiveTypes *)getPrimitiveTypes:(nonnull PrimitiveTypes *)recordType
 NS_SWIFT_NAME(getPrimitiveTypes(recordType:));
+ (nonnull CollectionTypes *)getCollectionTypes:(nonnull CollectionTypes *)recordType
 NS_SWIFT_NAME(getCollectionTypes(recordType:));
+ (nonnull OptionalTypes *)getOptionalTypes:(nonnull OptionalTypes *)recordType
 NS_SWIFT_NAME(getOptionalTypes(recordType:));
+ (nonnull BinaryTypes *)getBinaryTypes:(nonnull BinaryTypes *)recordType
 NS_SWIFT_NAME(getBinaryTypes(recordType:));
+ (nonnull BaseRecord *)getCppBaseRecord NS_SWIFT_NAME(getCppBaseRecord());
+ (nonnull BaseRecord *)getHostBaseRecord:(nonnull BaseRecord *)recordType
 NS_SWIFT_NAME(getHostBaseRecord(recordType:));
@end
