// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#import <Foundation/Foundation.h>

NS_SWIFT_NAME(OptionalTypes)
@interface OptionalTypes : NSObject
- (nonnull instancetype)initWithIntOptional:(nullable NSNumber *)intOptional stringOptional:(nullable NSString *)stringOptional;
+ (nonnull instancetype)optionalTypesWithIntOptional:(nullable NSNumber *)intOptional stringOptional:(nullable NSString *)stringOptional;
@property (nonatomic, readonly, nullable) NSNumber * intOptional;
@property (nonatomic, readonly, nullable) NSString * stringOptional;
@end
