// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#import <Foundation/Foundation.h>
#import "NestedType.h"

NS_SWIFT_NAME(ParentType)
@interface ParentType : NSObject
- (nonnull instancetype)initWithNested:(nonnull NestedType *)nested;
+ (nonnull instancetype)parentTypeWithNested:(nonnull NestedType *)nested;
@property (nonatomic, readonly, nonnull) NestedType * nested;
@end
