// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTPrimitiveTypes.h"
#import "TSTCollectionTypes.h"
#import "TSTOptionalTypes.h"
#import "TSTBinaryTypes.h"
#import "TSTBaseRecord.h"
#import "TSTParentType.h"

NS_SWIFT_NAME(Helper)
@interface TSTHelper : NSObject
+ (nonnull TSTPrimitiveTypes *)getPrimitiveTypes:(nonnull TSTPrimitiveTypes *)recordType
  NS_SWIFT_NAME(getPrimitiveTypes(recordType:));
+ (nonnull TSTCollectionTypes *)getCollectionTypes:(nonnull TSTCollectionTypes *)recordType
  NS_SWIFT_NAME(getCollectionTypes(recordType:));
+ (nonnull TSTOptionalTypes *)getOptionalTypes:(nonnull TSTOptionalTypes *)recordType
  NS_SWIFT_NAME(getOptionalTypes(recordType:));
+ (nonnull TSTBinaryTypes *)getBinaryTypes:(nonnull TSTBinaryTypes *)recordType
  NS_SWIFT_NAME(getBinaryTypes(recordType:));
+ (nonnull TSTBaseRecord *)getCppBaseRecord  NS_SWIFT_NAME(getCppBaseRecord());
+ (nonnull TSTBaseRecord *)getHostBaseRecord:(nonnull TSTBaseRecord *)recordType
  NS_SWIFT_NAME(getHostBaseRecord(recordType:));
+ (nonnull TSTParentType *)getNestedType:(nonnull TSTParentType *)parent
  NS_SWIFT_NAME(getNestedType(parent:));
@end
