// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(PrimitiveTypes)
@interface TSTPrimitiveTypes : NSObject
- (nonnull instancetype)initWithBooleanT:(BOOL)booleanT byteT:(int8_t)byteT shortT:(int16_t)shortT intT:(int32_t)intT longT:(int64_t)longT floatT:(float)floatT doubleT:(double)doubleT stringT:(nonnull NSString *)stringT dateT:(nonnull NSDate *)dateT;
+ (nonnull instancetype)primitiveTypesWithBooleanT:(BOOL)booleanT byteT:(int8_t)byteT shortT:(int16_t)shortT intT:(int32_t)intT longT:(int64_t)longT floatT:(float)floatT doubleT:(double)doubleT stringT:(nonnull NSString *)stringT dateT:(nonnull NSDate *)dateT;
@property (nonatomic, readonly) BOOL booleanT;
@property (nonatomic, readonly) int8_t byteT;
@property (nonatomic, readonly) int16_t shortT;
@property (nonatomic, readonly) int32_t intT;
@property (nonatomic, readonly) int64_t longT;
@property (nonatomic, readonly) float floatT;
@property (nonatomic, readonly) double doubleT;
@property (nonatomic, readonly, nonnull) NSString * stringT;
@property (nonatomic, readonly, nonnull) NSDate * dateT;
@end
