// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "pydjinni/cppcli/Marshal.hpp"
#include "readonly_property_data.hpp"
namespace Test::Properties::CppCli {
public ref class ReadonlyPropertyData sealed  {
public:
    ReadonlyPropertyData(int changeCounter, System::String^ callbackValue, System::String^ readValue);

    property int ChangeCounter
    {
        int get();
    }
    property System::String^ CallbackValue
    {
        System::String^ get();
    }
    property System::String^ ReadValue
    {
        System::String^ get();
    }
    System::String^ ToString() override;
internal:
    using CppType = ::test::properties::ReadonlyPropertyData;
    using CsType = ReadonlyPropertyData^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    int _changeCounter;
    System::String^ _callbackValue;
    System::String^ _readValue;
};
} // namespace Test::Properties::CppCli
