// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "pydjinni/cppcli/Marshal.hpp"
#include "readwrite_property_data.hpp"
namespace Test::Properties::CppCli {
public ref class ReadwritePropertyData sealed  {
public:
    ReadwritePropertyData(int changeCounter, __int64 callbackValue, __int64 readValue);

    property int ChangeCounter
    {
        int get();
    }
    property __int64 CallbackValue
    {
        __int64 get();
    }
    property __int64 ReadValue
    {
        __int64 get();
    }
    System::String^ ToString() override;
internal:
    using CppType = ::test::properties::ReadwritePropertyData;
    using CsType = ReadwritePropertyData^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    int _changeCounter;
    __int64 _callbackValue;
    __int64 _readValue;
};
} // namespace Test::Properties::CppCli
