// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "host_properties.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Properties::CppCli {
/**
 * <summary>
 * <para>property class owned by the host language</para>
 * </summary>
 */
public ref class HostProperties abstract : System::ComponentModel::INotifyPropertyChanged {
public:
    virtual event System::ComponentModel::PropertyChangedEventHandler ^ PropertyChanged;
    property __int64 ReadwriteProperty {
        __int64 get() { return _readwriteProperty; }
        void set(__int64 value) { 
            _readwriteProperty = value;
            OnPropertyChanged("ReadwriteProperty");
         }
    }
    property System::String^ ReadonlyProperty {
        System::String^ get() { return _readonlyProperty; }
        protected: void set(System::String^ value) { 
            _readonlyProperty = value;
            OnPropertyChanged("ReadonlyProperty");
         }
    }
    property System::Nullable<__int64> OptionalProperty {
        System::Nullable<__int64> get() { return _optionalProperty; }
        void set(System::Nullable<__int64> value) { 
            _optionalProperty = value;
            OnPropertyChanged("OptionalProperty");
         }
    }
    virtual void ChangeReadonlyProperty() abstract;
internal:
    using CppType = std::shared_ptr<::test::properties::HostProperties>;
    using CppOptType = std::shared_ptr<::test::properties::HostProperties>;
    using CsType = HostProperties^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
    __int64 _readwriteProperty;
    System::String^ _readonlyProperty;
    System::Nullable<__int64> _optionalProperty;
    void OnPropertyChanged(System::String^ propertyName)
    {
        PropertyChanged(this, gcnew System::ComponentModel::PropertyChangedEventArgs(propertyName));
    }
};
} // namespace Test::Properties::CppCli
