// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "cpp_properties.hpp"
#include "CppCliCppProperties.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Properties::CppCli {
public ref class CppProperties abstract : System::ComponentModel::INotifyPropertyChanged {
public:
    virtual event System::ComponentModel::PropertyChangedEventHandler ^ PropertyChanged;
    /**
     * <summary>
     * <para>this property has a comment</para>
     * </summary>
     */
    property __int64 ReadwriteProperty {
        virtual __int64 get() { return _readwriteProperty; }
        virtual void set(__int64 value) { 
            _readwriteProperty = value;
            OnPropertyChanged("ReadwriteProperty");
         }
    }
    property System::String^ ReadonlyProperty {
        virtual System::String^ get() { return _readonlyProperty; }
        protected: virtual void set(System::String^ value) { 
            _readonlyProperty = value;
            OnPropertyChanged("ReadonlyProperty");
         }
    }
    property System::Nullable<__int64> OptionalProperty {
        virtual System::Nullable<__int64> get() { return _optionalProperty; }
        virtual void set(System::Nullable<__int64> value) { 
            _optionalProperty = value;
            OnPropertyChanged("OptionalProperty");
         }
    }
    [System::Obsolete("this property should not be used!")]
    property System::Collections::Generic::List<System::String^>^ DeprecatedProperty {
        virtual System::Collections::Generic::List<System::String^>^ get() { return _deprecatedProperty; }
        virtual void set(System::Collections::Generic::List<System::String^>^ value) { 
            _deprecatedProperty = value;
            OnPropertyChanged("DeprecatedProperty");
         }
    }
    static ::Test::Properties::CppCli::CppProperties^ GetInstance();
    virtual void ChangeReadonlyProperty() abstract;
internal:
    using CppType = std::shared_ptr<::test::properties::CppProperties>;
    using CppOptType = std::shared_ptr<::test::properties::CppProperties>;
    using CsType = CppProperties^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
    __int64 _readwriteProperty;
    System::String^ _readonlyProperty;
    System::Nullable<__int64> _optionalProperty;
    System::Collections::Generic::List<System::String^>^ _deprecatedProperty;
    void OnPropertyChanged(System::String^ propertyName)
    {
        PropertyChanged(this, gcnew System::ComponentModel::PropertyChangedEventArgs(propertyName));
    }
};
} // namespace Test::Properties::CppCli
