// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "optional_property_data.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Properties::CppCli {
public ref class OptionalPropertyData sealed  {
public:
    OptionalPropertyData(int changeCounter, System::Nullable<__int64> callbackValue, System::Nullable<__int64> readValue);

    property int ChangeCounter
    {
        int get();
    }
    property System::Nullable<__int64> CallbackValue
    {
        System::Nullable<__int64> get();
    }
    property System::Nullable<__int64> ReadValue
    {
        System::Nullable<__int64> get();
    }
    System::String^ ToString() override;
internal:
    using CppType = ::test::properties::OptionalPropertyData;
    using CsType = OptionalPropertyData^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    int _changeCounter;
    System::Nullable<__int64> _callbackValue;
    System::Nullable<__int64> _readValue;
};
} // namespace Test::Properties::CppCli
