// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "CppCliHostProperties.hpp"
#include "CppCliHostPropertyHelper.hpp"
#include "CppCliOptionalPropertyData.hpp"
#include "CppCliReadonlyPropertyData.hpp"
#include "CppCliReadwritePropertyData.hpp"
#include "host_property_helper.hpp"
namespace Test::Properties::CppCli {
public ref class HostPropertyHelper abstract {
public:
    static ::Test::Properties::CppCli::HostPropertyHelper^ Setup(::Test::Properties::CppCli::HostProperties^ properties);
    virtual ::Test::Properties::CppCli::ReadwritePropertyData^ ReadwritePropertyData() abstract;
    virtual void ModifyHostReadwriteProperty() abstract;
    virtual ::Test::Properties::CppCli::ReadonlyPropertyData^ ReadonlyPropertyData() abstract;
    virtual ::Test::Properties::CppCli::OptionalPropertyData^ OptionalPropertyData() abstract;
internal:
    using CppType = std::shared_ptr<::test::properties::HostPropertyHelper>;
    using CppOptType = std::shared_ptr<::test::properties::HostPropertyHelper>;
    using CsType = HostPropertyHelper^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};
} // namespace Test::Properties::CppCli
