// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'flags.pydjinni'
#import <Foundation/Foundation.h>
typedef NS_OPTIONS(NSUInteger, SFTExampleFlags) {
    SFTExampleFlagsA = 1u << 0,
    SFTExampleFlagsB = 1u << 1,
    SFTExampleFlagsAll = 0 | SFTExampleFlagsA | SFTExampleFlagsB,
    SFTExampleFlagsNone = 0
}
NS_SWIFT_NAME(ExampleFlags);
