// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
package test.function_test;

@FunctionalInterface
public interface Function_Cpp_Cppcli_Java_Objc_Foo_Bool {
    boolean invoke(test.function_test.Foo param);
}

final class Function_Cpp_Cppcli_Java_Objc_Foo_BoolCppProxy implements Function_Cpp_Cppcli_Java_Objc_Foo_Bool {
    private final long nativeRef;

    static class CleanupTask implements Runnable {
        private final long nativeRef;
        CleanupTask(long nativeRef) {
            this.nativeRef = nativeRef;
        }

        @Override
        public void run() {
            nativeDestroy(this.nativeRef);
        }

        private native void nativeDestroy(long nativeRef);
    }

    private Function_Cpp_Cppcli_Java_Objc_Foo_BoolCppProxy(long nativeRef)
    {
        if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
        this.nativeRef = nativeRef;
        test.function_test.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
    }

    @Override
    public boolean invoke(test.function_test.Foo param) {
        return nativeInvoke(this.nativeRef, param);
    }
    private native boolean nativeInvoke(long _nativeRef, test.function_test.Foo param);
}
