// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
package test.function_test;

@FunctionalInterface
public interface Function_Cpp_Cppcli_Java_Objc_Void_Throws_Bar {
    void invoke();
}

final class Function_Cpp_Cppcli_Java_Objc_Void_Throws_BarCppProxy implements Function_Cpp_Cppcli_Java_Objc_Void_Throws_Bar {
    private final long nativeRef;

    static class CleanupTask implements Runnable {
        private final long nativeRef;
        CleanupTask(long nativeRef) {
            this.nativeRef = nativeRef;
        }

        @Override
        public void run() {
            nativeDestroy(this.nativeRef);
        }

        private native void nativeDestroy(long nativeRef);
    }

    private Function_Cpp_Cppcli_Java_Objc_Void_Throws_BarCppProxy(long nativeRef)
    {
        if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
        this.nativeRef = nativeRef;
        test.function_test.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
    }

    @Override
    public void invoke() {
         nativeInvoke(this.nativeRef);
    }
    private native void nativeInvoke(long _nativeRef);
}
