// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <cstdint>

namespace test::record {
struct BaseRecord;
struct BaseRecordBase {
    const int32_t value;
    BaseRecordBase(int32_t value_)
    : value(std::move(value_))
    {}

};
}  // namespace test::record
