// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <format>

namespace test::record {
struct BaseRecord;
struct BaseRecordBase {
    const int32_t value;
    BaseRecordBase(int32_t value)
    : value(std::move(value))
    {}
};
} // namespace test::record
