// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <optional>
#include <vector>

namespace test::record {
struct BinaryTypes final {
    const std::vector<uint8_t> binary_t;
    const std::optional<std::vector<uint8_t>> binary_optional;
    BinaryTypes(std::vector<uint8_t> binary_t_, std::optional<std::vector<uint8_t>> binary_optional_)
    : binary_t(std::move(binary_t_))
    , binary_optional(std::move(binary_optional_))
    {}

};
}  // namespace test::record
