// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <ostream>
#include <version>
#ifdef __cpp_lib_format
#include <format>
#endif
#include <vector>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <unordered_map>

namespace test::record {
struct CollectionTypes final {
    const std::vector<int32_t> int_list;
    const std::vector<std::string> string_list;
    const std::unordered_set<int32_t> int_set;
    const std::unordered_set<std::string> string_set;
    const std::unordered_map<int32_t, int32_t> int_int_map;
    const std::unordered_map<std::string, std::string> string_string_map;
    CollectionTypes(std::vector<int32_t> int_list_, std::vector<std::string> string_list_, std::unordered_set<int32_t> int_set_, std::unordered_set<std::string> string_set_, std::unordered_map<int32_t, int32_t> int_int_map_, std::unordered_map<std::string, std::string> string_string_map_)
    : int_list(std::move(int_list_))
    , string_list(std::move(string_list_))
    , int_set(std::move(int_set_))
    , string_set(std::move(string_set_))
    , int_int_map(std::move(int_int_map_))
    , string_string_map(std::move(string_string_map_))
    {}

    friend std::ostream& operator<<( std::ostream& os, CollectionTypes const& value ) {
        os << "::test::record::CollectionTypes(";
        os << "int_list={?}, ";
        os << "string_list={?}, ";
        os << "int_set={?}, ";
        os << "string_set={?}, ";
        os << "int_int_map={?}, ";
        os << "string_string_map={?}";
        os << ")";
        return os;
    }
};
}  // namespace test::record
#ifdef __cpp_lib_format
template <>
struct std::formatter<::test::record::CollectionTypes> {
    auto format(const ::test::record::CollectionTypes& obj, std::format_context& ctx) const {
        return std::format_to(ctx.out(), "::test::record::CollectionTypes(int_list={}, string_list={}, int_set={}, string_set={}, int_int_map={}, string_string_map={})", obj.int_list, obj.string_list, obj.int_set, obj.string_set, obj.int_int_map, obj.string_string_map);
    }
};
#endif
