// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <ostream>
#include <iomanip>
#include <version>
#ifdef __cpp_lib_format
#include <format>
#endif
#include <cstdint>
#include <vector>

namespace test::record {
struct NestedType final {
    const int32_t a;
    const std::vector<std::vector<int32_t>> b;
    NestedType(int32_t a_, std::vector<std::vector<int32_t>> b_)
    : a(std::move(a_))
    , b(std::move(b_))
    {}

    friend std::ostream& operator<<(std::ostream& os, NestedType const& value);
};
}  // namespace test::record
