// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include "pydjinni/deprecated.hpp"
#include <algorithm>
#include <format>

namespace test::record {
/**
 * deprecated record with comments
 * 
 * @deprecated
 */
struct [[deprecated]] OldRecord final {
    /**
     * more comment
     */
    const bool a;
    /**
     * @param a more comment
     */
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
    OldRecord(bool a)
    : a(std::move(a))
    {}
PYDJINNI_ENABLE_WARNINGS
};
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
std::string to_string(const ::test::record::OldRecord& value);
PYDJINNI_ENABLE_WARNINGS
} // namespace test::record
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
template<>
struct std::formatter<::test::record::OldRecord> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::record::OldRecord& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::record::to_string(value));
    }
};
PYDJINNI_ENABLE_WARNINGS
