// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include <algorithm>
#include <ostream>
#include <iomanip>
#include <version>
#ifdef __cpp_lib_format
#include <format>
#endif
#include <cstdint>
#include <string>
#include <optional>

namespace test::record {
struct OptionalTypes final {
    const std::optional<int32_t> int_optional;
    const std::optional<std::string> string_optional;
    OptionalTypes(std::optional<int32_t> int_optional_, std::optional<std::string> string_optional_)
    : int_optional(std::move(int_optional_))
    , string_optional(std::move(string_optional_))
    {}

    friend std::ostream& operator<<(std::ostream& os, OptionalTypes const& value);
};
}  // namespace test::record
