// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <optional>
#include <cstdint>
#include <string>

namespace test::record {
struct OptionalTypes final {
    std::optional<int32_t> int_optional;
    std::optional<std::string> string_optional;
    OptionalTypes(std::optional<int32_t> int_optional_, std::optional<std::string> string_optional_)
    : int_optional(std::move(int_optional_))
    , string_optional(std::move(string_optional_))
    {}

};
}  // namespace test::record
