// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <format>
#include <optional>
#include <string>

namespace test::record {
struct OptionalTypes final {
    const std::optional<int32_t> int_optional;
    const std::optional<std::string> string_optional;
    OptionalTypes(std::optional<int32_t> int_optional, std::optional<std::string> string_optional)
    : int_optional(std::move(int_optional))
    , string_optional(std::move(string_optional))
    {}
};
std::string to_string(const ::test::record::OptionalTypes& value);
} // namespace test::record
template<>
struct std::formatter<::test::record::OptionalTypes> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::record::OptionalTypes& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::record::to_string(value));
    }
};
