// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <ostream>
#include <iomanip>
#include <version>
#ifdef __cpp_lib_format
#include <format>
#endif
#include "nested_type.hpp"

namespace test::record {
struct ParentType final {
    const ::test::record::NestedType nested;
    ParentType(::test::record::NestedType nested_)
    : nested(std::move(nested_))
    {}

    friend std::ostream& operator<<(std::ostream& os, ParentType const& value);
};
}  // namespace test::record
