// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#pragma once
#include "nested_type.hpp"
#include <algorithm>
#include <format>

namespace test::record {
struct ParentType final {
    const ::test::record::NestedType nested;
    ParentType(::test::record::NestedType nested)
    : nested(std::move(nested))
    {}
};
std::string to_string(const ::test::record::ParentType& value);
} // namespace test::record
template<>
struct std::formatter<::test::record::ParentType> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::record::ParentType& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::record::to_string(value));
    }
};
