// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <string>
#include <chrono>

namespace test::record {
struct PrimitiveTypes final {
    bool boolean_t;
    int8_t byte_t;
    int16_t short_t;
    int32_t int_t;
    int64_t long_t;
    float float_t;
    double double_t;
    std::string string_t;
    std::chrono::system_clock::time_point date_t;
    PrimitiveTypes(bool boolean_t_, int8_t byte_t_, int16_t short_t_, int32_t int_t_, int64_t long_t_, float float_t_, double double_t_, std::string string_t_, std::chrono::system_clock::time_point date_t_)
    : boolean_t(std::move(boolean_t_))
    , byte_t(std::move(byte_t_))
    , short_t(std::move(short_t_))
    , int_t(std::move(int_t_))
    , long_t(std::move(long_t_))
    , float_t(std::move(float_t_))
    , double_t(std::move(double_t_))
    , string_t(std::move(string_t_))
    , date_t(std::move(date_t_))
    {}

};
}  // namespace test::record
