// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'flags.pydjinni'
#pragma once

namespace Test::Flags::CppCli {
[System::Flags]
public enum class ExampleFlags {
    A = 1u << 0,
    B = 1u << 1,
    All = 0 | A | B,
    None = 0
};
}  // namespace Test::Flags::CppCli
