// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#pragma once
#include <memory>
#include <cstdint>
#include "pydjinni/coroutine/task.hpp"

namespace test::async_test {
class MultiplyCallback {
public:
    virtual pydjinni::coroutine::task<int32_t> invoke(int32_t a, int32_t b) noexcept = 0;
};
}  // namespace test::async_test
