// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#pragma once
#include "pydjinni/coroutine/task.hpp"
#include <cstdint>
#include <memory>

namespace test::async_test {
class MultiplyCallback {
public:
    virtual ~MultiplyCallback() = default;
    virtual pydjinni::coroutine::task<int32_t> invoke(int32_t a, int32_t b) noexcept = 0;
};
} // namespace test::async_test
