// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTSomethingNamespacedNamespacedRecord.h"
@interface TSTGlobalInterface : NSObject
+ (nonnull TSTSomethingNamespacedNamespacedRecord *)getNamespacedRecord;
@end
