// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
@interface TSTSomethingNamespacedOtherNamespacedRecord : NSObject
- (nonnull instancetype)initWithA:(int32_t)a;
+ (nonnull instancetype)otherNamespacedRecordWithA:(int32_t)a;
@property (nonatomic, readonly) int32_t a;
@end
