// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTGlobalRecord.h"
@interface TSTSomethingNamespacedNamespacedInterface : NSObject
+ (nonnull TSTGlobalRecord *)getGlobalRecord;
@end
