// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'namespace.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTGlobalRecord.h"
@interface TSTSomethingNamespacedNamespacedRecord : NSObject
- (nonnull instancetype)initWithA:(nonnull TSTGlobalRecord *)a;
+ (nonnull instancetype)namespacedRecordWithA:(nonnull TSTGlobalRecord *)a;
@property (nonatomic, readonly, nonnull) TSTGlobalRecord * a;
@end
