/*#
Copyright 2024 jothepro

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
#*/
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni
#pragma once
#include "pydjinni/coroutine/continuation_runner.hpp"
#include "pydjinni/jni/support.hpp"

namespace {{ namespace }} {

    class NativeRunnable final : ::pydjinni::JniInterface<pydjinni::coroutine::ContinuationRunner, NativeRunnable> {
    public:

        ~NativeRunnable() = default;

        static ::pydjinni::LocalRef<jobject> fromCpp(JNIEnv* jniEnv, const pydjinni::coroutine::ContinuationRunner& c) {
            return {jniEnv, ::pydjinni::JniClass<NativeRunnable>::get()._toJava(jniEnv, std::make_shared<pydjinni::coroutine::ContinuationRunner>(c))};
        }
    private:
        NativeRunnable() : ::pydjinni::JniInterface<pydjinni::coroutine::ContinuationRunner, NativeRunnable>("{{ java_type_signature }}") {};
        friend ::pydjinni::JniClass<NativeRunnable>;
        friend ::pydjinni::JniInterface<pydjinni::coroutine::ContinuationRunner, NativeRunnable>;
    };

    void forkJoinPool(const pydjinni::coroutine::ContinuationRunner& runner);
}

