// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni

#import <Foundation/Foundation.h>
//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "SFTExampleEnum.h"
#import "SFTEnumWithComments.h"
#import "SFTDeprecatedEnum.h"
#import "SFTDeprecatedEnumItem.h"
#import "SFTHelper.h"
