// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#import <Foundation/Foundation.h>
/// this is a multiline comment
typedef NS_ENUM(NSUInteger, SFTEnumWithComments) {
    /// first value
    SFTEnumWithCommentsFirst,
    /// second value
    SFTEnumWithCommentsSecond
}
NS_SWIFT_NAME(EnumWithComments);
