// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#import <Foundation/Foundation.h>
#import "Calculator.h"
#import "PlatformInterface.h"

NS_SWIFT_NAME(Calculator)
@interface Calculator : NSObject
+ (nullable Calculator *)getInstance NS_SWIFT_NAME(getInstance());
/// adds up two values
/// 
/// - Parameter a: the first value
/// - Parameter b: the second value
/// - Returns: the sum of both values
- (int8_t)add:(int8_t)a
            b:(int8_t)b
 NS_SWIFT_NAME(add(a:b:));
- (int8_t)getPlatformValue:(nullable id<PlatformInterface>)platform
 NS_SWIFT_NAME(getPlatformValue(platform:));
- (void)noParametersNoReturn NS_SWIFT_NAME(noParametersNoReturn());
- (void)throwingException NS_SWIFT_NAME(throwingException());
@end
