// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#import <Foundation/Foundation.h>

/// 
NS_SWIFT_NAME(DeprecationTest)
__attribute__((deprecated("testing class deprecation annotation")))
@protocol DeprecationTest <NSObject>
/// 
- (int32_t)deprecationTest  __attribute__((deprecated("testing method deprecation annotation")))
  __attribute__((swift_name("deprecationTest()")));
@end
