// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#import <Foundation/Foundation.h>

NS_SWIFT_NAME(DeprecationTest)
DEPRECATED_MSG_ATTRIBUTE("testing class deprecation annotation")
@protocol DeprecationTest <NSObject>
- (int32_t)deprecationTest DEPRECATED_MSG_ATTRIBUTE("testing method deprecation annotation")
 NS_SWIFT_NAME(deprecationTest());
@end
