// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#import <Foundation/Foundation.h>

NS_SWIFT_NAME(PlatformInterface)
@protocol PlatformInterface <NSObject>
- (int8_t)getValue  __attribute__((swift_name("getValue()")));
@end
