// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTCalculator.h"
#import "TSTPlatformInterface.h"

NS_SWIFT_NAME(Calculator)
@interface TSTCalculator : NSObject
+ (nullable TSTCalculator *)getInstance  NS_SWIFT_NAME(getInstance());
/// adds up two values
/// 
/// - Parameter a: the first value
/// - Parameter b: the second value
/// - Returns: the sum of both values
- (int8_t)add:(int8_t)a
            b:(int8_t)b
  NS_SWIFT_NAME(add(a:b:));
- (int8_t)getPlatformValue:(nullable id<TSTPlatformInterface>)platform
  NS_SWIFT_NAME(getPlatformValue(platform:));
- (void)noParametersNoReturn  NS_SWIFT_NAME(noParametersNoReturn());
- (void)throwingException  NS_SWIFT_NAME(throwingException());
@end
