// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni

#import <Foundation/Foundation.h>
//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "SFTAsynchronous.h"
#import "SFTMultiplyCallback.h"
#import "SFTNoParametersNoReturnCallback.h"
#import "SFTThrowingCallback.h"
