// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTAsynchronous.h"
#import "SFTMultiplyCallback.h"
#import "SFTNoParametersNoReturnCallback.h"
#import "SFTThrowingCallback.h"
NS_SWIFT_NAME(Asynchronous)
@interface SFTAsynchronous : NSObject
+ (void)getInstance:(nonnull void (^)(SFTAsynchronous * _Nonnull))completion
  NS_SWIFT_NAME(getInstance(completion:));
- (void)add:(int32_t)a b:(int32_t)b completion:(nonnull void (^)(int32_t ))completion
  NS_SWIFT_NAME(add(a:b:completion:));
- (void)noParametersNoReturn:(nonnull void (^)(void ))completion
  NS_SWIFT_NAME(noParametersNoReturn(completion:));
- (void)throwingException:(nonnull void (^)(NSError* _Nullable))completion
  __attribute__((swift_async_error(nonnull_error)))
  NS_SWIFT_NAME(throwingException(completion:));
- (void)multiplyCallback:(nonnull id<SFTMultiplyCallback>)callback completion:(nonnull void (^)(int32_t ))completion
  NS_SWIFT_NAME(multiplyCallback(callback:completion:));
- (void)noParametersNoReturnCallback:(nonnull id<SFTNoParametersNoReturnCallback>)callback completion:(nonnull void (^)(void ))completion
  NS_SWIFT_NAME(noParametersNoReturnCallback(callback:completion:));
- (void)throwingCallback:(nonnull id<SFTThrowingCallback>)callback completion:(nonnull void (^)(NSError* _Nullable))completion
  __attribute__((swift_async_error(nonnull_error)))
  NS_SWIFT_NAME(throwingCallback(callback:completion:));
- (void)returningOptional:(nonnull void (^)(NSNumber * _Nullable))completion
  NS_SWIFT_NAME(returningOptional(completion:));
@end
