// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(ThrowingCallback)
@protocol SFTThrowingCallback 
- (void)invoke:(nonnull void (^)(NSError* _Nullable))completion
  __attribute__((swift_async_error(nonnull_error)))
  NS_SWIFT_NAME(invoke(completion:));
@end
