// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
NS_SWIFT_NAME(MultiplyCallback)
@protocol TSTMultiplyCallback 
- (void)invoke:(int32_t)a b:(int32_t)b completion:(nonnull void (^)(int32_t ))completion
  NS_SWIFT_NAME(invoke(a:b:completion:));
@end
