// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'flags.pydjinni'
#import <Foundation/Foundation.h>
typedef NS_OPTIONS(NSUInteger, TSTExampleFlags) {
    TSTExampleFlagsA = 1u << 0,
    TSTExampleFlagsB = 1u << 1,
    TSTExampleFlagsAll = 0 | TSTExampleFlagsA | TSTExampleFlagsB,
    TSTExampleFlagsNone = 0
};
