// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include "pydjinni/deprecated.hpp"
#include <format>

namespace test::enum_test {
/**
 * @deprecated this enum is old
 */
enum class [[deprecated("this enum is old")]] DeprecatedEnum : int {
    FIRST
};
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
std::string to_string(::test::enum_test::DeprecatedEnum value) noexcept;
PYDJINNI_ENABLE_WARNINGS
} // namespace test::enum_test
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
template<>
struct std::formatter<::test::enum_test::DeprecatedEnum> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(test::enum_test::DeprecatedEnum value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::enum_test::to_string(value));
    }
};
PYDJINNI_ENABLE_WARNINGS
