// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include <format>

namespace test::enum_test {
/**
 * this is a multiline comment
 */
enum class EnumWithComments : int {
    /**
     * first value
     */
    FIRST,
    /**
     * second value
     */
    SECOND
};
std::string to_string(::test::enum_test::EnumWithComments value) noexcept;
} // namespace test::enum_test
template<>
struct std::formatter<::test::enum_test::EnumWithComments> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(test::enum_test::EnumWithComments value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::enum_test::to_string(value));
    }
};
