// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include <format>

namespace test::enum_test {
enum class ExampleEnum : int {
    A,
    B,
    C
};
std::string to_string(::test::enum_test::ExampleEnum value) noexcept;
} // namespace test::enum_test
template<>
struct std::formatter<::test::enum_test::ExampleEnum> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(test::enum_test::ExampleEnum value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::enum_test::to_string(value));
    }
};
