// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include <ostream>

namespace test::enum_test {
enum class ExampleEnum : int {
    A,
    B,
    C
};

std::ostream& operator<<(std::ostream& os, ExampleEnum value);
}  // namespace test::enum_test
