/*#
Copyright 2024 jothepro

        Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
        limitations under the License.
#*/
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni
#include {{ header_path | quote }}

namespace {{ namespace }} {

void forkJoinPool(const pydjinni::coroutine::ContinuationRunner& runner) {
    auto forkJoinPoolClass = ::pydjinni::jniFindClass("java/util/concurrent/ForkJoinPool");
    auto commonPoolMethod = ::pydjinni::jniGetStaticMethodID(forkJoinPoolClass.get(), "commonPool", "()Ljava/util/concurrent/ForkJoinPool;");
    auto executeMethod = ::pydjinni::jniGetMethodID(forkJoinPoolClass.get(), "execute", "(Ljava/lang/Runnable;)V");
    auto jniEnv = ::pydjinni::jniGetThreadEnv();
    auto commonPool = jniEnv->CallStaticObjectMethod(forkJoinPoolClass.get(), commonPoolMethod);
    ::pydjinni::jniExceptionCheck(jniEnv);
    jniEnv->CallVoidMethod(commonPool, executeMethod, NativeRunnable::fromCpp(jniEnv, runner).get());
}

extern "C" {

[[maybe_unused]] JNIEXPORT void JNICALL {{ jni_prefix }}_nativeRun(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef) noexcept {
    ::pydjinni::translate_exceptions(jniEnv, [&]() {
        ::pydjinni::objectFromHandleAddress<pydjinni::coroutine::ContinuationRunner>(nativeRef)->run();
    });
}

[[maybe_unused]] JNIEXPORT void JNICALL {{ jni_prefix }}_00024CleanupTask_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef) noexcept {
    delete reinterpret_cast<::pydjinni::CppProxyHandle<pydjinni::coroutine::ContinuationRunner>*>(nativeRef);
}

}

}
