// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "cpp_properties.hpp"
#include "pydjinni/signals.hpp"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace test::properties {
class CppProperties {
    pydjinni::signals::signal<int64_t> _signal_readwrite_property_changed;
    int64_t _readwrite_property;
    pydjinni::signals::signal<const std::string &> _signal_readonly_property_changed;
    std::string _readonly_property;
    pydjinni::signals::signal<std::optional<int64_t>> _signal_optional_property_changed;
    std::optional<int64_t> _optional_property;
    pydjinni::signals::signal<const std::vector<std::string> &> _signal_deprecated_property_changed;
    std::vector<std::string> _deprecated_property;
public:
    virtual ~CppProperties() = default;
    static std::shared_ptr<::test::properties::CppProperties> get_instance() noexcept;
    virtual void change_readonly_property() noexcept = 0;
    /**
     * this property has a comment
     */
    [[nodiscard]] int64_t get_readwrite_property() const noexcept;
    /**
     * this property has a comment
     */
    pydjinni::signals::connection on_readwrite_property_changed(const std::function<void(int64_t)>& callback) noexcept;
    /**
     * this property has a comment
     */
    virtual void set_readwrite_property(int64_t value) noexcept;
    [[nodiscard]] std::string get_readonly_property() const noexcept;
    pydjinni::signals::connection on_readonly_property_changed(const std::function<void(const std::string &)>& callback) noexcept;
protected:
    virtual void set_readonly_property(const std::string & value) noexcept;
public:
    [[nodiscard]] std::optional<int64_t> get_optional_property() const noexcept;
    pydjinni::signals::connection on_optional_property_changed(const std::function<void(std::optional<int64_t>)>& callback) noexcept;
    virtual void set_optional_property(std::optional<int64_t> value) noexcept;
    /**
     * @deprecated this property should not be used!
     */
    [[deprecated("this property should not be used!")]] 
    [[nodiscard]] std::vector<std::string> get_deprecated_property() const noexcept;
    /**
     * @deprecated this property should not be used!
     */
    [[deprecated("this property should not be used!")]] 
    pydjinni::signals::connection on_deprecated_property_changed(const std::function<void(const std::vector<std::string> &)>& callback) noexcept;
    /**
     * @deprecated this property should not be used!
     */
    [[deprecated("this property should not be used!")]] 
    virtual void set_deprecated_property(const std::vector<std::string> & value) noexcept;
};
} // namespace test::properties
