// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "pydjinni/signals.hpp"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>

namespace test::properties {
/**
 * property class owned by the host language
 */
class HostProperties {
    pydjinni::signals::signal<int64_t> _signal_readwrite_property_changed;
    int64_t _readwrite_property;
    pydjinni::signals::signal<const std::string &> _signal_readonly_property_changed;
    std::string _readonly_property;
    pydjinni::signals::signal<std::optional<int64_t>> _signal_optional_property_changed;
    std::optional<int64_t> _optional_property;
public:
    virtual ~HostProperties() = default;
    virtual void change_readonly_property() noexcept = 0;
    [[nodiscard]] int64_t get_readwrite_property() const noexcept;
    pydjinni::signals::connection on_readwrite_property_changed(const std::function<void(int64_t)>& callback) noexcept;
    virtual void set_readwrite_property(int64_t value) noexcept;
    [[nodiscard]] std::string get_readonly_property() const noexcept;
    pydjinni::signals::connection on_readonly_property_changed(const std::function<void(const std::string &)>& callback) noexcept;
protected:
    virtual void set_readonly_property(const std::string & value) noexcept;
public:
    [[nodiscard]] std::optional<int64_t> get_optional_property() const noexcept;
    pydjinni::signals::connection on_optional_property_changed(const std::function<void(std::optional<int64_t>)>& callback) noexcept;
    virtual void set_optional_property(std::optional<int64_t> value) noexcept;
};
} // namespace test::properties
