// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include "host_properties.hpp"
#include "host_property_helper.hpp"
#include "optional_property_data.hpp"
#include "readonly_property_data.hpp"
#include "readwrite_property_data.hpp"
#include <memory>

namespace test::properties {
class HostPropertyHelper {
public:
    virtual ~HostPropertyHelper() = default;
    static std::shared_ptr<::test::properties::HostPropertyHelper> setup(const std::shared_ptr<::test::properties::HostProperties> & properties) noexcept;
    virtual ::test::properties::ReadwritePropertyData readwrite_property_data() noexcept = 0;
    virtual void modify_host_readwrite_property() noexcept = 0;
    virtual ::test::properties::ReadonlyPropertyData readonly_property_data() noexcept = 0;
    virtual ::test::properties::OptionalPropertyData optional_property_data() noexcept = 0;
};
} // namespace test::properties
