// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <format>
#include <optional>

namespace test::properties {
struct OptionalPropertyData final {
    const int32_t change_counter;
    const std::optional<int64_t> callback_value;
    const std::optional<int64_t> read_value;
    OptionalPropertyData(int32_t change_counter, std::optional<int64_t> callback_value, std::optional<int64_t> read_value)
    : change_counter(std::move(change_counter))
    , callback_value(std::move(callback_value))
    , read_value(std::move(read_value))
    {}
};
std::string to_string(const ::test::properties::OptionalPropertyData& value);
} // namespace test::properties
template<>
struct std::formatter<::test::properties::OptionalPropertyData> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::properties::OptionalPropertyData& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::properties::to_string(value));
    }
};
