// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <format>

namespace test::properties {
struct ReadwritePropertyData final {
    const int32_t change_counter;
    const int64_t callback_value;
    const int64_t read_value;
    ReadwritePropertyData(int32_t change_counter, int64_t callback_value, int64_t read_value)
    : change_counter(std::move(change_counter))
    , callback_value(std::move(callback_value))
    , read_value(std::move(read_value))
    {}
};
std::string to_string(const ::test::properties::ReadwritePropertyData& value);
} // namespace test::properties
template<>
struct std::formatter<::test::properties::ReadwritePropertyData> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::properties::ReadwritePropertyData& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::properties::to_string(value));
    }
};
