// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
#pragma once
#include <algorithm>
#include <cstdint>
#include <format>
#include <string>

namespace test::properties {
struct ReadonlyPropertyData final {
    const int32_t change_counter;
    const std::string callback_value;
    const std::string read_value;
    ReadonlyPropertyData(int32_t change_counter, std::string callback_value, std::string read_value)
    : change_counter(std::move(change_counter))
    , callback_value(std::move(callback_value))
    , read_value(std::move(read_value))
    {}
};
std::string to_string(const ::test::properties::ReadonlyPropertyData& value);
} // namespace test::properties
template<>
struct std::formatter<::test::properties::ReadonlyPropertyData> : std::formatter<std::string> {
    template<typename FormatContext>
    auto format(const ::test::properties::ReadonlyPropertyData& value, FormatContext &ctx) const {
        return std::format_to(ctx.out(), "{}", test::properties::to_string(value));
    }
};
