// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
package test.interface_test;

public abstract class OptionalInterface {
    static {
        test.interface_test.pydjinni.NativeInterfaceTestKotlinJniLoader.loadLibrary();
    }
    public static test.interface_test.@org.jetbrains.annotations.Nullable OptionalInterface getInstance() {
        return CppProxy.getInstance();
    };
    public static test.interface_test.@org.jetbrains.annotations.Nullable OptionalInterface getNullInstance() {
        return CppProxy.getNullInstance();
    };
    public abstract @org.jetbrains.annotations.Nullable String optionalParameter(@org.jetbrains.annotations.Nullable String param);
    public abstract @org.jetbrains.annotations.Nullable String optionalNullParameter(@org.jetbrains.annotations.Nullable String param);
    private static final class CppProxy extends OptionalInterface {
        private final long nativeRef;

        static class CleanupTask implements Runnable {
            private final long nativeRef;
            CleanupTask(long nativeRef) {
                this.nativeRef = nativeRef;
            }

            @Override
            public void run() {
                nativeDestroy(this.nativeRef);
            }

            private native void nativeDestroy(long nativeRef);
        }

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            test.interface_test.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
        }

        public static native test.interface_test.@org.jetbrains.annotations.Nullable OptionalInterface getInstance();
        public static native test.interface_test.@org.jetbrains.annotations.Nullable OptionalInterface getNullInstance();
        @Override
        public @org.jetbrains.annotations.Nullable String optionalParameter(@org.jetbrains.annotations.Nullable String param) {
            return native_optionalParameter(this.nativeRef , param);
        }
        private native @org.jetbrains.annotations.Nullable String native_optionalParameter(long _nativeRef, @org.jetbrains.annotations.Nullable String param);
        @Override
        public @org.jetbrains.annotations.Nullable String optionalNullParameter(@org.jetbrains.annotations.Nullable String param) {
            return native_optionalNullParameter(this.nativeRef , param);
        }
        private native @org.jetbrains.annotations.Nullable String native_optionalNullParameter(long _nativeRef, @org.jetbrains.annotations.Nullable String param);
    }
}
