// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
package test.interface_test;

public abstract class PlatformInterface {
    @org.jetbrains.annotations.NotNull
    public abstract byte getValue();
}
