// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include "enum_with_comments.hpp"
namespace Test::Enum::CppCli {
/**
 * <summary>
 * <para>this is a multiline comment</para>
 * </summary>
 */
public enum class EnumWithComments {
    /**
     * <summary>
     * <para>first value</para>
     * </summary>
     */
    First,
    /**
     * <summary>
     * <para>second value</para>
     * </summary>
     */
    Second
};
} // namespace Test::Enum::CppCli
