// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include "deprecated_enum.hpp"
namespace Test::Enum::CppCli {
[System::Obsolete("this enum is old")]
public enum class DeprecatedEnum {
    First
};
} // namespace Test::Enum::CppCli
