// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once
#include "deprecated_enum_item.hpp"
namespace Test::Enum::CppCli {
public enum class DeprecatedEnumItem {
    [System::Obsolete("this enum item is outdated")]
    Outdated
};
} // namespace Test::Enum::CppCli
