// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#pragma once

namespace Test::Enum::CppCli {
public enum class ExampleEnum {
    A,
    B,
    C
};
}  // namespace Test::Enum::CppCli
