// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni

#import <Foundation/Foundation.h>
//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "TSTPrimitiveTypes.h"
#import "TSTCollectionTypes.h"
#import "TSTOptionalTypes.h"
#import "TSTBinaryTypes.h"
#import "TSTBaseRecord.h"
#import "TSTNestedType.h"
#import "TSTParentType.h"
#import "TSTHelper.h"
#import "TSTOldRecord.h"
#import "TSTDeprecatedFieldRecord.h"
