// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
/// deprecated record with comments
DEPRECATED_ATTRIBUTE
NS_SWIFT_NAME(OldRecord)
@interface SFTOldRecord : NSObject
- (nonnull instancetype)initWithA:(BOOL)a;
+ (nonnull instancetype)oldRecordWithA:(BOOL)a;
/// more comment
@property (nonatomic, readonly) BOOL a;
@end
