// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
#import <Foundation/Foundation.h>
#import "SFTNestedType.h"
NS_SWIFT_NAME(ParentType)
@interface SFTParentType : NSObject
- (nonnull instancetype)initWithNested:(nonnull SFTNestedType *)nested;
+ (nonnull instancetype)parentTypeWithNested:(nonnull SFTNestedType *)nested;
@property (nonatomic, readonly, nonnull) SFTNestedType * nested;
@end
