// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.djinni'
#pragma once
#include <functional>
#include <vcclr.h>
#include <cstdint>

namespace Test::Function::CppCli {

ref class _FunctionI32BoolDelegateCppProxy
{
public:
    _FunctionI32BoolDelegateCppProxy(const std::function<bool(int32_t)>& lambda) : _lambda(new std::function<bool(int32_t)>(lambda)) {}
    ~_FunctionI32BoolDelegateCppProxy();
    !_FunctionI32BoolDelegateCppProxy();

    bool Invoke(int param);
private:
    std::function<bool(int32_t)>* _lambda;
};

class _FunctionI32BoolDelegate {
public:
    using CppType = std::function<bool(int32_t)>;
    using CsType = System::Func<int, bool>^;

    static CppType ToCpp(gcroot<CsType> delegate);
    static CsType FromCpp(const CppType& function);
};
}  // namespace Test::Function::CppCli
