// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#pragma once
#include "function_string_bool.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
#include <functional>
#include <vcclr.h>
namespace Test::Function::CppCli {
ref class _FunctionStringBoolDelegateCppProxy
{
public:
    _FunctionStringBoolDelegateCppProxy(const std::function<bool(std::string)>& lambda) : _lambda(new std::function<bool(std::string)>(lambda)) {}
    ~_FunctionStringBoolDelegateCppProxy();
    !_FunctionStringBoolDelegateCppProxy();

    bool Invoke(System::String^ param);
private:
    std::function<bool(std::string)>* _lambda;
};

class _FunctionStringBoolDelegate {
public:
    using CppType = std::function<bool(std::string)>;
    using CsType = System::Func<System::String^, bool>^;

    static CppType ToCpp(gcroot<CsType> delegate);
    static CsType FromCpp(const CppType& function);
};
} // namespace Test::Function::CppCli
