// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#pragma once
#include "bar.hpp"
namespace Test::Function::CppCli {
public ref class Bar abstract : System::Exception {
public:
    Bar();
    Bar(System::String^ message);
    ref class BadStuff;
};

ref class Bar::BadStuff : Bar {
public:
    BadStuff();
    BadStuff(System::String^ message);

internal:
    using CppType = ::test::function::Bar::BadStuff;
    using CsType = BadStuff^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
};
} // namespace Test::Function::CppCli
