// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#pragma once
#include "function_cpp_cppcli_java_objc_string_bool.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
#include <functional>
#include <vcclr.h>
namespace Test::Function::CppCli {
ref class _FunctionCppCppcliJavaObjcStringBoolDelegateCppProxy
{
public:
    _FunctionCppCppcliJavaObjcStringBoolDelegateCppProxy(const std::function<bool(std::string)>& lambda) : _lambda(new std::function<bool(std::string)>(lambda)) {}
    ~_FunctionCppCppcliJavaObjcStringBoolDelegateCppProxy();
    !_FunctionCppCppcliJavaObjcStringBoolDelegateCppProxy();

    bool Invoke(System::String^ param);
private:
    std::function<bool(std::string)>* _lambda;
};

class _FunctionCppCppcliJavaObjcStringBoolDelegate {
public:
    using CppType = std::function<bool(std::string)>;
    using CppOptType = std::function<bool(std::string)>;
    using CsType = System::Func<System::String^, bool>^;

    static CppType ToCpp(gcroot<CsType> delegate);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp);
};
} // namespace Test::Function::CppCli
