// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#pragma once
#include "foo.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Function::CppCli {
public ref class Foo sealed  {
public:
    Foo(int a);

    property int A
    {
        int get();
    }
internal:
    using CppType = ::test::function::Foo;
    using CsType = Foo^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);
private:
    int _a;
};
} // namespace Test::Function::CppCli
