// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#pragma once
#include "named_function.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
#include <functional>
#include <vcclr.h>
namespace Test::Function::CppCli {
public delegate bool NamedFunction(System::String^ param);
ref class _NamedFunctionDelegateCppProxy
{
public:
    _NamedFunctionDelegateCppProxy(const std::function<bool(std::string)>& lambda) : _lambda(new std::function<bool(std::string)>(lambda)) {}
    ~_NamedFunctionDelegateCppProxy();
    !_NamedFunctionDelegateCppProxy();

    bool Invoke(System::String^ param);
private:
    std::function<bool(std::string)>* _lambda;
};

class _NamedFunctionDelegate {
public:
    using CppType = std::function<bool(std::string)>;
    using CppOptType = std::function<bool(std::string)>;
    using CsType = ::Test::Function::CppCli::NamedFunction^;

    static CppType ToCpp(gcroot<CsType> delegate);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp);
};
} // namespace Test::Function::CppCli
