// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include "calculator.hpp"
#include "no_parameters_no_return_callback.hpp"
#include "platform_interface.hpp"
#include "throwing_callback.hpp"
#include <cstdint>
#include <memory>

namespace test::interface_test {
class Calculator {
public:
    virtual ~Calculator() = default;
    static std::shared_ptr<::test::interface_test::Calculator> get_instance() noexcept;
    /**
     * adds up two values
     * 
     * @param a the first value
     * @param b the second value
     * @returns the sum of both values
     */
    [[nodiscard]] virtual int8_t add(int8_t a, int8_t b) const noexcept = 0;
    virtual int8_t get_platform_value(const std::shared_ptr<::test::interface_test::PlatformInterface> & platform) noexcept = 0;
    virtual void no_parameters_no_return() noexcept = 0;
    virtual void throwing_exception() = 0;
    virtual void no_parameters_no_return_callback(const std::shared_ptr<::test::interface_test::NoParametersNoReturnCallback> & callback) noexcept = 0;
    virtual void throwing_callback(const std::shared_ptr<::test::interface_test::ThrowingCallback> & callback) = 0;
};
} // namespace test::interface_test
