// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#pragma once
#include <memory>
#include "calculator.hpp"
#include <cstdint>
#include "platform_interface.hpp"

namespace test::interface {
class Calculator {
public:
    static std::shared_ptr<::test::interface::Calculator> get_instance();
    /**
     * adds up two values
     * 
     * @param a the first value
     * @param b the second value
     * @returns the sum of both values
     */
    virtual int8_t add(int8_t a, int8_t b) = 0;
    virtual int8_t get_platform_value(const std::shared_ptr<::test::interface::PlatformInterface> & platform) = 0;
    virtual void no_parameters_no_return() = 0;
    virtual void throwing_exception() = 0;
};
}  // namespace test::interface
