// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include <memory>

namespace test::interface_test {
class DeprecatedMethodTest {
public:
    virtual ~DeprecatedMethodTest() = default;
    /**
     * @deprecated this method is deprecated but the type is not
     */
    [[deprecated("this method is deprecated but the type is not")]] 
    virtual bool deprecated_test_method() noexcept = 0;
};
} // namespace test::interface_test
