// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include <memory>
#include <cstdint>

namespace test::interface_test {
/**
 * @deprecated testing class deprecation annotation
 */
class [[deprecated("testing class deprecation annotation")]] DeprecationTest {
public:
    /**
     * @deprecated testing method deprecation annotation
     */
    [[deprecated("testing method deprecation annotation")]]
    virtual int32_t deprecation_test_method() noexcept = 0;
};
}  // namespace test::interface_test
