// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include <memory>

namespace test::interface_test {
class NoParametersNoReturnCallback {
public:
    virtual ~NoParametersNoReturnCallback() = default;
    virtual void invoke() noexcept = 0;
};
} // namespace test::interface_test
