// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include <memory>
#include <cstdint>

namespace test::interface_test {
class PlatformInterface {
public:
    virtual int8_t get_value() noexcept = 0;
};
}  // namespace test::interface_test
