// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.djinni'
#pragma once
#include <memory>
#include <cstdint>

namespace test::interface {
class PlatformInterface {
public:
    virtual int8_t get_value() = 0;
};
}  // namespace test::interface
