// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include <memory>

namespace test::interface_test {
class ThrowingCallback {
public:
    virtual ~ThrowingCallback() = default;
    virtual void invoke() const = 0;
};
} // namespace test::interface_test
