// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#include "deprecated_enum.hpp"

namespace test::enum_test {
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
std::string to_string(::test::enum_test::DeprecatedEnum value) noexcept {
    switch(value) {
        case ::test::enum_test::DeprecatedEnum::FIRST: return "FIRST";
    }
    return {};
}
PYDJINNI_ENABLE_WARNINGS
} // namespace test::enum_test
