// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#include "deprecated_enum_item.hpp"
#include "pydjinni/deprecated.hpp"

namespace test::enum_test {
std::string to_string(::test::enum_test::DeprecatedEnumItem value) noexcept {
    switch(value) {
PYDJINNI_DISABLE_DEPRECATED_WARNINGS
        case ::test::enum_test::DeprecatedEnumItem::OUTDATED: return "OUTDATED";
PYDJINNI_ENABLE_WARNINGS
    }
    return {};
}
} // namespace test::enum_test
