// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#include "enum_with_comments.hpp"

namespace test::enum_test {
std::string to_string(::test::enum_test::EnumWithComments value) noexcept {
    switch(value) {
        case ::test::enum_test::EnumWithComments::FIRST: return "FIRST";
        case ::test::enum_test::EnumWithComments::SECOND: return "SECOND";
    }
    return {};
}
} // namespace test::enum_test
