// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#include "example_enum.hpp"

namespace test::enum_test {
std::string to_string(::test::enum_test::ExampleEnum value) noexcept {
    switch(value) {
        case ::test::enum_test::ExampleEnum::A: return "A";
        case ::test::enum_test::ExampleEnum::B: return "B";
        case ::test::enum_test::ExampleEnum::C: return "C";
    }
    return {};
}
} // namespace test::enum_test
