// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#import <Foundation/Foundation.h>
typedef NS_ENUM(NSUInteger, TSTDeprecatedEnum) {
    TSTDeprecatedEnumFirst
}
DEPRECATED_MSG_ATTRIBUTE("this enum is old");
