// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#import <Foundation/Foundation.h>
typedef NS_ENUM(NSUInteger, TSTDeprecatedEnumItem) {
    TSTDeprecatedEnumItemOutdated
};
