// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'enum.pydjinni'
#import <Foundation/Foundation.h>
/// this is a multiline comment
typedef NS_ENUM(NSUInteger, TSTEnumWithComments) {
    /// first value
    TSTEnumWithCommentsFirst,
    /// second value
    TSTEnumWithCommentsSecond
};
