// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTAsynchronous.h"
#import "TSTMultiplyCallback.h"
#import "TSTNoParametersNoReturnCallback.h"
#import "TSTThrowingCallback.h"
@interface TSTAsynchronous : NSObject
+ (void)getInstance:(nonnull void (^)(TSTAsynchronous * _Nonnull))completion;
- (void)add:(int32_t)a b:(int32_t)b completion:(nonnull void (^)(int32_t ))completion;
- (void)noParametersNoReturn:(nonnull void (^)(void ))completion;
- (void)throwingException:(nonnull void (^)(NSError* _Nullable))completion;
- (void)multiplyCallback:(nonnull id<TSTMultiplyCallback>)callback completion:(nonnull void (^)(int32_t ))completion;
- (void)noParametersNoReturnCallback:(nonnull id<TSTNoParametersNoReturnCallback>)callback completion:(nonnull void (^)(void ))completion;
- (void)throwingCallback:(nonnull id<TSTThrowingCallback>)callback completion:(nonnull void (^)(NSError* _Nullable))completion;
- (void)returningOptional:(nonnull void (^)(NSNumber * _Nullable))completion;
@end
