// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTMultiplyCallback 
- (void)invoke:(int32_t)a b:(int32_t)b completion:(nonnull void (^)(int32_t ))completion;
@end
