// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTNoParametersNoReturnCallback 
- (void)invoke:(nonnull void (^)(void ))completion;
@end
