// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTThrowingCallback 
- (void)invoke:(nonnull void (^)(NSError* _Nullable))completion;
@end
