// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

public abstract class CppProperties {
    static {
        test.properties_test.pydjinni.NativePropertiesTestJniLoader.loadLibrary();
    }
    private long _readwriteProperty;
    private test.properties_test.pydjinni.Signal<Long> _readwritePropertySignal = new test.properties_test.pydjinni.Signal<Long>();
    private String _readonlyProperty;
    private test.properties_test.pydjinni.Signal<String> _readonlyPropertySignal = new test.properties_test.pydjinni.Signal<String>();
    private Long _optionalProperty;
    private test.properties_test.pydjinni.Signal<Long> _optionalPropertySignal = new test.properties_test.pydjinni.Signal<Long>();
    private java.util.ArrayList<String> _deprecatedProperty;
    private test.properties_test.pydjinni.Signal<java.util.ArrayList<String>> _deprecatedPropertySignal = new test.properties_test.pydjinni.Signal<java.util.ArrayList<String>>();
    public static test.properties_test.CppProperties getInstance() {
        return CppProxy.getInstance();
    };
    public abstract void changeReadonlyProperty();
    /**
     * this property has a comment
     */
    public long getReadwriteProperty() {
        return _readwriteProperty;
    }
    public test.properties_test.pydjinni.Connection onReadwritePropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
        return _readwritePropertySignal.connect(callback);
    };
    /**
     * this property has a comment
     */
    public void setReadwriteProperty(long value) {
        _readwriteProperty = value;
        _readwritePropertySignal.notify(_readwriteProperty);
    };
    public String getReadonlyProperty() {
        return _readonlyProperty;
    }
    public test.properties_test.pydjinni.Connection onReadonlyPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<String> callback) {
        return _readonlyPropertySignal.connect(callback);
    };
    protected void setReadonlyProperty(String value) {
        _readonlyProperty = value;
        _readonlyPropertySignal.notify(_readonlyProperty);
    };
    public Long getOptionalProperty() {
        return _optionalProperty;
    }
    public test.properties_test.pydjinni.Connection onOptionalPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
        return _optionalPropertySignal.connect(callback);
    };
    public void setOptionalProperty(Long value) {
        _optionalProperty = value;
        _optionalPropertySignal.notify(_optionalProperty);
    };
    /**
     * @deprecated this property should not be used!
     */
    @Deprecated
    public java.util.ArrayList<String> getDeprecatedProperty() {
        return _deprecatedProperty;
    }
    @Deprecated
    public test.properties_test.pydjinni.Connection onDeprecatedPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<java.util.ArrayList<String>> callback) {
        return _deprecatedPropertySignal.connect(callback);
    };
    /**
     * @deprecated this property should not be used!
     */
    @Deprecated
    public void setDeprecatedProperty(java.util.ArrayList<String> value) {
        _deprecatedProperty = value;
        _deprecatedPropertySignal.notify(_deprecatedProperty);
    };
    private static final class CppProxy extends CppProperties {
        private final long nativeRef;

        private test.properties_test.pydjinni.Connection readwritePropertyConnection;
        private test.properties_test.pydjinni.Connection readonlyPropertyConnection;
        private test.properties_test.pydjinni.Connection optionalPropertyConnection;
        private test.properties_test.pydjinni.Connection deprecatedPropertyConnection;
        static class CleanupTask implements Runnable {
            private final long nativeRef;
            CleanupTask(long nativeRef) {
                this.nativeRef = nativeRef;
            }

            @Override
            public void run() {
                nativeDestroy(this.nativeRef);
            }

            private native void nativeDestroy(long nativeRef);
        }

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            test.properties_test.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
        }

        private void lazyInitreadwriteProperty() {
            if(readwritePropertyConnection == null) {
                readwritePropertyConnection = native_onReadwritePropertyChanged(this.nativeRef, (newValue) -> {
                    super.setReadwriteProperty(newValue);
                });
                super.setReadwriteProperty(this.native_getReadwriteProperty(this.nativeRef));
            }
        }

        @Override
        public long getReadwriteProperty() {
            lazyInitreadwriteProperty();
            return super.getReadwriteProperty();
        }

        private native long native_getReadwriteProperty(long _nativeRef);

        @Override
        public test.properties_test.pydjinni.Connection onReadwritePropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
            lazyInitreadwriteProperty();
            return super.onReadwritePropertyChanged(callback);
        }

        private native test.properties_test.pydjinni.Connection native_onReadwritePropertyChanged(long _nativeRef, test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback);

        @Override
        public void setReadwriteProperty(long value) {
            lazyInitreadwriteProperty();
            native_setReadwriteProperty(this.nativeRef, value);
        }

        private native void native_setReadwriteProperty(long _nativeRef, long value);
        private void lazyInitreadonlyProperty() {
            if(readonlyPropertyConnection == null) {
                readonlyPropertyConnection = native_onReadonlyPropertyChanged(this.nativeRef, (newValue) -> {
                    super.setReadonlyProperty(newValue);
                });
                super.setReadonlyProperty(this.native_getReadonlyProperty(this.nativeRef));
            }
        }

        @Override
        public String getReadonlyProperty() {
            lazyInitreadonlyProperty();
            return super.getReadonlyProperty();
        }

        private native String native_getReadonlyProperty(long _nativeRef);

        @Override
        public test.properties_test.pydjinni.Connection onReadonlyPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<String> callback) {
            lazyInitreadonlyProperty();
            return super.onReadonlyPropertyChanged(callback);
        }

        private native test.properties_test.pydjinni.Connection native_onReadonlyPropertyChanged(long _nativeRef, test.properties_test.pydjinni.OnPropertyChangedCallback<String> callback);

        private void lazyInitoptionalProperty() {
            if(optionalPropertyConnection == null) {
                optionalPropertyConnection = native_onOptionalPropertyChanged(this.nativeRef, (newValue) -> {
                    super.setOptionalProperty(newValue);
                });
                super.setOptionalProperty(this.native_getOptionalProperty(this.nativeRef));
            }
        }

        @Override
        public Long getOptionalProperty() {
            lazyInitoptionalProperty();
            return super.getOptionalProperty();
        }

        private native Long native_getOptionalProperty(long _nativeRef);

        @Override
        public test.properties_test.pydjinni.Connection onOptionalPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
            lazyInitoptionalProperty();
            return super.onOptionalPropertyChanged(callback);
        }

        private native test.properties_test.pydjinni.Connection native_onOptionalPropertyChanged(long _nativeRef, test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback);

        @Override
        public void setOptionalProperty(Long value) {
            lazyInitoptionalProperty();
            native_setOptionalProperty(this.nativeRef, value);
        }

        private native void native_setOptionalProperty(long _nativeRef, Long value);
        private void lazyInitdeprecatedProperty() {
            if(deprecatedPropertyConnection == null) {
                deprecatedPropertyConnection = native_onDeprecatedPropertyChanged(this.nativeRef, (newValue) -> {
                    super.setDeprecatedProperty(newValue);
                });
                super.setDeprecatedProperty(this.native_getDeprecatedProperty(this.nativeRef));
            }
        }

        @Override
        public java.util.ArrayList<String> getDeprecatedProperty() {
            lazyInitdeprecatedProperty();
            return super.getDeprecatedProperty();
        }

        private native java.util.ArrayList<String> native_getDeprecatedProperty(long _nativeRef);

        @Override
        public test.properties_test.pydjinni.Connection onDeprecatedPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<java.util.ArrayList<String>> callback) {
            lazyInitdeprecatedProperty();
            return super.onDeprecatedPropertyChanged(callback);
        }

        private native test.properties_test.pydjinni.Connection native_onDeprecatedPropertyChanged(long _nativeRef, test.properties_test.pydjinni.OnPropertyChangedCallback<java.util.ArrayList<String>> callback);

        @Override
        public void setDeprecatedProperty(java.util.ArrayList<String> value) {
            lazyInitdeprecatedProperty();
            native_setDeprecatedProperty(this.nativeRef, value);
        }

        private native void native_setDeprecatedProperty(long _nativeRef, java.util.ArrayList<String> value);
        public static native test.properties_test.CppProperties getInstance();
        @Override
        public void changeReadonlyProperty() {
            native_changeReadonlyProperty(this.nativeRef);
        }
        private native void native_changeReadonlyProperty(long _nativeRef);
    }
}
