// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

/**
 * property class owned by the host language
 */
public abstract class HostProperties {
    private long _readwriteProperty;
    private test.properties_test.pydjinni.Signal<Long> _readwritePropertySignal = new test.properties_test.pydjinni.Signal<Long>();
    private String _readonlyProperty;
    private test.properties_test.pydjinni.Signal<String> _readonlyPropertySignal = new test.properties_test.pydjinni.Signal<String>();
    private Long _optionalProperty;
    private test.properties_test.pydjinni.Signal<Long> _optionalPropertySignal = new test.properties_test.pydjinni.Signal<Long>();
    public abstract void changeReadonlyProperty();
    public long getReadwriteProperty() {
        return _readwriteProperty;
    }
    public test.properties_test.pydjinni.Connection onReadwritePropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
        return _readwritePropertySignal.connect(callback);
    };
    public void setReadwriteProperty(long value) {
        _readwriteProperty = value;
        _readwritePropertySignal.notify(_readwriteProperty);
    };
    public String getReadonlyProperty() {
        return _readonlyProperty;
    }
    public test.properties_test.pydjinni.Connection onReadonlyPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<String> callback) {
        return _readonlyPropertySignal.connect(callback);
    };
    protected void setReadonlyProperty(String value) {
        _readonlyProperty = value;
        _readonlyPropertySignal.notify(_readonlyProperty);
    };
    public Long getOptionalProperty() {
        return _optionalProperty;
    }
    public test.properties_test.pydjinni.Connection onOptionalPropertyChanged(test.properties_test.pydjinni.OnPropertyChangedCallback<Long> callback) {
        return _optionalPropertySignal.connect(callback);
    };
    public void setOptionalProperty(Long value) {
        _optionalProperty = value;
        _optionalPropertySignal.notify(_optionalProperty);
    };
}
