// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

public abstract class HostPropertyHelper {
    static {
        test.properties_test.pydjinni.NativePropertiesTestJniLoader.loadLibrary();
    }
    public static test.properties_test.HostPropertyHelper setup(test.properties_test.HostProperties properties) {
        return CppProxy.setup(properties);
    };
    public abstract test.properties_test.ReadwritePropertyData readwritePropertyData();
    public abstract void modifyHostReadwriteProperty();
    public abstract test.properties_test.ReadonlyPropertyData readonlyPropertyData();
    public abstract test.properties_test.OptionalPropertyData optionalPropertyData();
    private static final class CppProxy extends HostPropertyHelper {
        private final long nativeRef;

        static class CleanupTask implements Runnable {
            private final long nativeRef;
            CleanupTask(long nativeRef) {
                this.nativeRef = nativeRef;
            }

            @Override
            public void run() {
                nativeDestroy(this.nativeRef);
            }

            private native void nativeDestroy(long nativeRef);
        }

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            test.properties_test.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
        }

        public static native test.properties_test.HostPropertyHelper setup(test.properties_test.HostProperties properties);
        @Override
        public test.properties_test.ReadwritePropertyData readwritePropertyData() {
            return native_readwritePropertyData(this.nativeRef);
        }
        private native test.properties_test.ReadwritePropertyData native_readwritePropertyData(long _nativeRef);
        @Override
        public void modifyHostReadwriteProperty() {
            native_modifyHostReadwriteProperty(this.nativeRef);
        }
        private native void native_modifyHostReadwriteProperty(long _nativeRef);
        @Override
        public test.properties_test.ReadonlyPropertyData readonlyPropertyData() {
            return native_readonlyPropertyData(this.nativeRef);
        }
        private native test.properties_test.ReadonlyPropertyData native_readonlyPropertyData(long _nativeRef);
        @Override
        public test.properties_test.OptionalPropertyData optionalPropertyData() {
            return native_optionalPropertyData(this.nativeRef);
        }
        private native test.properties_test.OptionalPropertyData native_optionalPropertyData(long _nativeRef);
    }
}
