// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

public final class OptionalPropertyData {
    final int changeCounter;
    final Long callbackValue;
    final Long readValue;
    public OptionalPropertyData(
        int changeCounter,
        Long callbackValue,
        Long readValue
    ) {
        this.changeCounter = changeCounter;
        this.callbackValue = callbackValue;
        this.readValue = readValue;
    }

    public int getChangeCounter() { return changeCounter; }
    public Long getCallbackValue() { return callbackValue; }
    public Long getReadValue() { return readValue; }
    @Override
    public String toString() {
        return "test.properties_test.OptionalPropertyData{" +
            "changeCounter=" + changeCounter +
            ",callbackValue=" + callbackValue +
            ",readValue=" + readValue +
        "}";
    }
}
