// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

public final class ReadonlyPropertyData {
    final int changeCounter;
    final String callbackValue;
    final String readValue;
    public ReadonlyPropertyData(
        int changeCounter,
        String callbackValue,
        String readValue
    ) {
        this.changeCounter = changeCounter;
        this.callbackValue = callbackValue;
        this.readValue = readValue;
    }

    public int getChangeCounter() { return changeCounter; }
    public String getCallbackValue() { return callbackValue; }
    public String getReadValue() { return readValue; }
    @Override
    public String toString() {
        return "test.properties_test.ReadonlyPropertyData{" +
            "changeCounter=" + changeCounter +
            ",callbackValue=" + callbackValue +
            ",readValue=" + readValue +
        "}";
    }
}
