// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'properties.pydjinni'
package test.properties_test;

public final class ReadwritePropertyData {
    final int changeCounter;
    final long callbackValue;
    final long readValue;
    public ReadwritePropertyData(
        int changeCounter,
        long callbackValue,
        long readValue
    ) {
        this.changeCounter = changeCounter;
        this.callbackValue = callbackValue;
        this.readValue = readValue;
    }

    public int getChangeCounter() { return changeCounter; }
    public long getCallbackValue() { return callbackValue; }
    public long getReadValue() { return readValue; }
    @Override
    public String toString() {
        return "test.properties_test.ReadwritePropertyData{" +
            "changeCounter=" + changeCounter +
            ",callbackValue=" + callbackValue +
            ",readValue=" + readValue +
        "}";
    }
}
