// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include "platform_interface.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Interface::CppCli {
public ref class PlatformInterface abstract {
public:
    virtual char GetValue() abstract;
internal:
    using CppType = std::shared_ptr<::test::interface_test::PlatformInterface>;
    using CppOptType = std::shared_ptr<::test::interface_test::PlatformInterface>;
    using CsType = PlatformInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};
} // namespace Test::Interface::CppCli
