// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#pragma once
#include "throwing_callback.hpp"
namespace Test::Interface::CppCli {
public ref class ThrowingCallback abstract {
public:
    virtual void Invoke() abstract;
internal:
    using CppType = std::shared_ptr<::test::interface_test::ThrowingCallback>;
    using CppOptType = std::shared_ptr<::test::interface_test::ThrowingCallback>;
    using CsType = ThrowingCallback^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};
} // namespace Test::Interface::CppCli
