// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'function.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTFunctionCppCppcliJavaObjcYamlFooBool.h"
#import "TSTFunctionCppCppcliJavaObjcYamlStringBool.h"
#import "TSTFunctionCppCppcliJavaObjcYamlVoidThrows.h"
#import "TSTFunctionCppCppcliJavaObjcYamlVoidThrowsBar.h"
#import "TSTNamedFunction.h"
#import "TSTThrowingFunction.h"
@interface TSTHelper : NSObject
+ (void)namedFunction:(BOOL (^)(NSString * _Nonnull))callback;
+ (void)anonymousFunction:(BOOL (^)(NSString * _Nonnull))callback;
+ (BOOL (^)(NSString * _Nonnull))cppNamedFunction;
+ (BOOL (^)(NSString * _Nonnull))cppAnonymousFunction;
+ (void (^)(NSError* _Nullable * _Nonnull))cppFunctionThrowingException;
+ (void (^)(NSError* _Nullable * _Nonnull))cppFunctionThrowingBarError;
+ (void)anonymousFunctionPassingRecord:(BOOL (^)(TSTFoo * _Nonnull))callback;
+ (void)functionParameterThrowing:(void (^)(NSError* _Nullable * _Nonnull))callback error:(NSError* _Nullable * _Nonnull)error;
@end
