// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#pragma once
#include "pydjinni/coroutine/callback_awaitable.hpp"
#include "pydjinni/coroutine/schedule.hpp"
#include "pydjinni/coroutine/task.hpp"
#include "throwing_callback.hpp"
namespace Test::Async::CppCli {
public ref class ThrowingCallback abstract {
public:
    virtual System::Threading::Tasks::Task^ Invoke() abstract;
internal:
    using CppType = std::shared_ptr<::test::async_test::ThrowingCallback>;
    using CppOptType = std::shared_ptr<::test::async_test::ThrowingCallback>;
    using CsType = ThrowingCallback^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
    ref class InvokeCallbackHandleProxy {
    public:
        InvokeCallbackHandleProxy(::pydjinni::coroutine::CallbackHandle<>& handle);
        void HandleCallback(System::Threading::Tasks::Task^ task);
    private:
        ::pydjinni::coroutine::CallbackHandle<>* _handle;
    };
};
} // namespace Test::Async::CppCli
