// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#pragma once
#include "multiply_callback.hpp"
#include "pydjinni/coroutine/callback_awaitable.hpp"
#include "pydjinni/coroutine/schedule.hpp"
#include "pydjinni/coroutine/task.hpp"
#include "pydjinni/cppcli/Marshal.hpp"
namespace Test::Async::CppCli {
public ref class MultiplyCallback abstract {
public:
    virtual System::Threading::Tasks::Task<int>^ Invoke(int a, int b) abstract;
internal:
    using CppType = std::shared_ptr<::test::async_test::MultiplyCallback>;
    using CppOptType = std::shared_ptr<::test::async_test::MultiplyCallback>;
    using CsType = MultiplyCallback^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
    ref class InvokeCallbackHandleProxy {
    public:
        InvokeCallbackHandleProxy(::pydjinni::coroutine::CallbackHandle<int32_t>& handle);
        void HandleCallback(System::Threading::Tasks::Task<int>^ task);
    private:
        ::pydjinni::coroutine::CallbackHandle<int32_t>* _handle;
    };
};
} // namespace Test::Async::CppCli
