// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public class BaseRecordBase {
    final int value;
    public BaseRecordBase(
        @org.jetbrains.annotations.NotNull
        int value
    ) {
        this.value = value;
    }

    @org.jetbrains.annotations.NotNull
    public int getValue() { return value; }
}
