// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public class BaseRecordBase {
    final @org.jetbrains.annotations.NotNull int value;
    public BaseRecordBase(
        @org.jetbrains.annotations.NotNull int value
    ) {
        this.value = value;
    }

    public @org.jetbrains.annotations.NotNull int getValue() { return value; }
    @Override
    public String toString() {
        return "test.record.BaseRecord{" +
            "value=" + value +
        "}";
    }
}
