// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class BinaryTypes {
    final @org.jetbrains.annotations.NotNull byte[] binaryT;
    final @org.jetbrains.annotations.Nullable byte[] binaryOptional;
    public BinaryTypes(
        @org.jetbrains.annotations.NotNull byte[] binaryT,
        @org.jetbrains.annotations.Nullable byte[] binaryOptional
    ) {
        this.binaryT = binaryT;
        this.binaryOptional = binaryOptional;
    }

    public @org.jetbrains.annotations.NotNull byte[] getBinaryT() { return binaryT; }
    public @org.jetbrains.annotations.Nullable byte[] getBinaryOptional() { return binaryOptional; }
    @Override
    public String toString() {
        return "test.record.BinaryTypes{" +
            "binaryT=" + binaryT +
            ",binaryOptional=" + binaryOptional +
        "}";
    }
}
