// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class BinaryTypes {
    final byte[] binaryT;
    final byte[] binaryOptional;
    public BinaryTypes(
        @org.jetbrains.annotations.NotNull
        byte[] binaryT,
        @org.jetbrains.annotations.Nullable
        byte[] binaryOptional
    ) {
        this.binaryT = binaryT;
        this.binaryOptional = binaryOptional;
    }

    @org.jetbrains.annotations.NotNull
    public byte[] getBinaryT() { return binaryT; }
    @org.jetbrains.annotations.Nullable
    public byte[] getBinaryOptional() { return binaryOptional; }
}
