// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class CollectionTypes {
    final java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull Integer> intList;
    final java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull String> stringList;
    final java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull Integer> intSet;
    final java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull String> stringSet;
    final java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull Integer, @org.jetbrains.annotations.NotNull Integer> intIntMap;
    final java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull String, @org.jetbrains.annotations.NotNull String> stringStringMap;
    public CollectionTypes(
        java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull Integer> intList,
        java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull String> stringList,
        java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull Integer> intSet,
        java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull String> stringSet,
        java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull Integer, @org.jetbrains.annotations.NotNull Integer> intIntMap,
        java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull String, @org.jetbrains.annotations.NotNull String> stringStringMap
    ) {
        this.intList = intList;
        this.stringList = stringList;
        this.intSet = intSet;
        this.stringSet = stringSet;
        this.intIntMap = intIntMap;
        this.stringStringMap = stringStringMap;
    }

    public java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull Integer> getIntList() { return intList; }
    public java.util.@org.jetbrains.annotations.NotNull ArrayList<@org.jetbrains.annotations.NotNull String> getStringList() { return stringList; }
    public java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull Integer> getIntSet() { return intSet; }
    public java.util.@org.jetbrains.annotations.NotNull HashSet<@org.jetbrains.annotations.NotNull String> getStringSet() { return stringSet; }
    public java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull Integer, @org.jetbrains.annotations.NotNull Integer> getIntIntMap() { return intIntMap; }
    public java.util.@org.jetbrains.annotations.NotNull HashMap<@org.jetbrains.annotations.NotNull String, @org.jetbrains.annotations.NotNull String> getStringStringMap() { return stringStringMap; }
    @Override
    public String toString() {
        return "test.record.CollectionTypes{" +
            "intList=" + intList +
            ",stringList=" + stringList +
            ",intSet=" + intSet +
            ",stringSet=" + stringSet +
            ",intIntMap=" + intIntMap +
            ",stringStringMap=" + stringStringMap +
        "}";
    }
}
