// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public abstract class Helper {
    static {
        test.record.pydjinni.NativeRecordTestKotlinJniLoader.loadLibrary();
    }
    public static test.record.@org.jetbrains.annotations.NotNull PrimitiveTypes getPrimitiveTypes(test.record.@org.jetbrains.annotations.NotNull PrimitiveTypes recordType) {
        return CppProxy.getPrimitiveTypes(recordType);
    };
    public static test.record.@org.jetbrains.annotations.NotNull CollectionTypes getCollectionTypes(test.record.@org.jetbrains.annotations.NotNull CollectionTypes recordType) {
        return CppProxy.getCollectionTypes(recordType);
    };
    public static test.record.@org.jetbrains.annotations.NotNull OptionalTypes getOptionalTypes(test.record.@org.jetbrains.annotations.NotNull OptionalTypes recordType) {
        return CppProxy.getOptionalTypes(recordType);
    };
    public static test.record.@org.jetbrains.annotations.NotNull BinaryTypes getBinaryTypes(test.record.@org.jetbrains.annotations.NotNull BinaryTypes recordType) {
        return CppProxy.getBinaryTypes(recordType);
    };
    public static test.record.@org.jetbrains.annotations.NotNull BaseRecord getCppBaseRecord() {
        return CppProxy.getCppBaseRecord();
    };
    public static test.record.@org.jetbrains.annotations.NotNull BaseRecord getHostBaseRecord(test.record.@org.jetbrains.annotations.NotNull BaseRecord recordType) {
        return CppProxy.getHostBaseRecord(recordType);
    };
    public static test.record.@org.jetbrains.annotations.NotNull ParentType getNestedType(test.record.@org.jetbrains.annotations.NotNull ParentType parent) {
        return CppProxy.getNestedType(parent);
    };
    private static final class CppProxy extends Helper {
        private final long nativeRef;

        static class CleanupTask implements Runnable {
            private final long nativeRef;
            CleanupTask(long nativeRef) {
                this.nativeRef = nativeRef;
            }

            @Override
            public void run() {
                nativeDestroy(this.nativeRef);
            }

            private native void nativeDestroy(long nativeRef);
        }

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            test.record.pydjinni.NativeCleaner.register(this, new CleanupTask(nativeRef));
        }

        public static native test.record.@org.jetbrains.annotations.NotNull PrimitiveTypes getPrimitiveTypes(test.record.@org.jetbrains.annotations.NotNull PrimitiveTypes recordType);
        public static native test.record.@org.jetbrains.annotations.NotNull CollectionTypes getCollectionTypes(test.record.@org.jetbrains.annotations.NotNull CollectionTypes recordType);
        public static native test.record.@org.jetbrains.annotations.NotNull OptionalTypes getOptionalTypes(test.record.@org.jetbrains.annotations.NotNull OptionalTypes recordType);
        public static native test.record.@org.jetbrains.annotations.NotNull BinaryTypes getBinaryTypes(test.record.@org.jetbrains.annotations.NotNull BinaryTypes recordType);
        public static native test.record.@org.jetbrains.annotations.NotNull BaseRecord getCppBaseRecord();
        public static native test.record.@org.jetbrains.annotations.NotNull BaseRecord getHostBaseRecord(test.record.@org.jetbrains.annotations.NotNull BaseRecord recordType);
        public static native test.record.@org.jetbrains.annotations.NotNull ParentType getNestedType(test.record.@org.jetbrains.annotations.NotNull ParentType parent);
    }
}
