// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class ParentType {
    final test.record.@org.jetbrains.annotations.NotNull NestedType nested;
    public ParentType(
        test.record.@org.jetbrains.annotations.NotNull NestedType nested
    ) {
        this.nested = nested;
    }

    public test.record.@org.jetbrains.annotations.NotNull NestedType getNested() { return nested; }
    @Override
    public String toString() {
        return "test.record.ParentType{" +
            "nested=" + nested +
        "}";
    }
}
