// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class ParentType {
    final test.record.NestedType nested;
    public ParentType(
        @org.jetbrains.annotations.NotNull
        test.record.NestedType nested
    ) {
        this.nested = nested;
    }

    @org.jetbrains.annotations.NotNull
    public test.record.NestedType getNested() { return nested; }
    @Override
    public String toString() {
        return "test.record.ParentType{" +
            "nested=" + nested +
        "}";
    }
}
