// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
#import "TSTCalculator.h"
#import "TSTNoParametersNoReturnCallback.h"
#import "TSTPlatformInterface.h"
#import "TSTThrowingCallback.h"
@interface TSTCalculator : NSObject
+ (nonnull TSTCalculator *)getInstance;
/// adds up two values
/// 
/// - Parameter a: the first value
/// - Parameter b: the second value
/// - Returns: the sum of both values
- (int8_t)add:(int8_t)a b:(int8_t)b;
- (int8_t)getPlatformValue:(nonnull id<TSTPlatformInterface>)platform;
- (void)noParametersNoReturn;
- (void)throwingException:(NSError* _Nullable * _Nonnull)error;
- (void)noParametersNoReturnCallback:(nonnull id<TSTNoParametersNoReturnCallback>)callback;
- (void)throwingCallback:(nonnull id<TSTThrowingCallback>)callback error:(NSError* _Nullable * _Nonnull)error;
@end
