// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTDeprecatedMethodTest <NSObject>
- (BOOL)deprecatedTestMethod
  DEPRECATED_MSG_ATTRIBUTE("this method is deprecated but the type is not");
@end
