// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
DEPRECATED_MSG_ATTRIBUTE("testing class deprecation annotation")
@protocol TSTDeprecationTest <NSObject>
- (int32_t)deprecationTestMethod
  DEPRECATED_MSG_ATTRIBUTE("testing method deprecation annotation");
@end
