// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTNoParametersNoReturnCallback <NSObject>
- (void)invoke;
@end
