// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTPlatformInterface <NSObject>
- (int8_t)getValue;
@end
