// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'interface.pydjinni'
#import <Foundation/Foundation.h>
@protocol TSTThrowingCallback <NSObject>
- (void)invoke:(NSError* _Nullable * _Nonnull)error;
@end
