// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
package test.async_test;

public abstract class MultiplyCallback {
    public abstract java.util.concurrent.CompletableFuture<Integer> invoke(int a, int b);
}
