// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
package test.async_test;

public abstract class NoParametersNoReturnCallback {
    public abstract java.util.concurrent.CompletableFuture<Void> invoke();
}
