// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'async.pydjinni'
#import <Foundation/Foundation.h>

NS_SWIFT_NAME(ThrowingCallback)
@protocol TSTThrowingCallback 
- (void)invoke:(nonnull void (^)(void ))completion
  NS_SWIFT_NAME(invoke(completion:));
@end
