// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public class BaseRecordBase {
    final int value;
    public BaseRecordBase(
        int value
    ) {
        this.value = value;
    }

    public int getValue() { return value; }
    @Override
    public String toString() {
        return "test.record.BaseRecord{" +
            "value=" + value +
        "}";
    }
}
