// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class BinaryTypes {
    final byte[] binaryT;
    final byte[] binaryOptional;
    public BinaryTypes(
        byte[] binaryT,
        byte[] binaryOptional
    ) {
        this.binaryT = binaryT;
        this.binaryOptional = binaryOptional;
    }

    public byte[] getBinaryT() { return binaryT; }
    public byte[] getBinaryOptional() { return binaryOptional; }
    @Override
    public String toString() {
        return "test.record.BinaryTypes{" +
            "binaryT=" + binaryT +
            ",binaryOptional=" + binaryOptional +
        "}";
    }
}
