// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.pydjinni'
package test.record;

public final class DeprecatedFieldRecord {
    final int old;
    final Integer older;
    public DeprecatedFieldRecord(
        int old,
        Integer older
    ) {
        this.old = old;
        this.older = older;
    }

    /**
     * @deprecated the field is old
     */
    @Deprecated
    public int getOld() { return old; }
    /**
     * foo
     * 
     * @deprecated this is optional and old
     */
    @Deprecated
    public Integer getOlder() { return older; }
    @Override
    public String toString() {
        return "test.record.DeprecatedFieldRecord{" +
            "old=" + old +
            ",older=" + older +
        "}";
    }
}
